/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * AccountSettingsApi - axios parameter creator
 * @export
 */
export const AccountSettingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get settings value
         * @param {number} id Address Book ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSettingsAddressBookFieldsById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSettingsAddressBookFieldsById', 'id', id)
            const localVarPath = `/api/settings/address-book-fields/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccountSettingsApi - functional programming interface
 * @export
 */
export const AccountSettingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AccountSettingsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get settings value
         * @param {number} id Address Book ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSettingsAddressBookFieldsById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSettingsAddressBookFieldsById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountSettingsApi.getSettingsAddressBookFieldsById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AccountSettingsApi - factory interface
 * @export
 */
export const AccountSettingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AccountSettingsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get settings value
         * @param {number} id Address Book ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSettingsAddressBookFieldsById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.getSettingsAddressBookFieldsById(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AccountSettingsApi - interface
 * @export
 * @interface AccountSettingsApi
 */
export interface AccountSettingsApiInterface {
    /**
     * 
     * @summary Get settings value
     * @param {number} id Address Book ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountSettingsApiInterface
     */
    getSettingsAddressBookFieldsById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<object>;

}

/**
 * AccountSettingsApi - object-oriented interface
 * @export
 * @class AccountSettingsApi
 * @extends {BaseAPI}
 */
export class AccountSettingsApi extends BaseAPI implements AccountSettingsApiInterface {
    /**
     * 
     * @summary Get settings value
     * @param {number} id Address Book ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountSettingsApi
     */
    public getSettingsAddressBookFieldsById(id: number, options?: RawAxiosRequestConfig) {
        return AccountSettingsApiFp(this.configuration).getSettingsAddressBookFieldsById(id, options).then((request) => request(this.axios, this.basePath));
    }
}

