/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AccountBalance200Response } from '../models';
// @ts-ignore
import type { AccountTariffs200Response } from '../models';
/**
 * BalanceApi - axios parameter creator
 * @export
 */
export const BalanceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Platform provides an API to get information about your account balance. The request allows you to obtain information about the current balance of your account, including the credit limit
         * @summary Get balance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountBalance: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/accounts/balance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This API allows you to get detailed information about the tariffs for sending SMS and Viber messages, as well as phone Number Verifier requests.  All rates are specified in the currency that is set in the account settings on the Platform.  The method transmits information about all available account tariffs for the SMS / 2 Way SMS, Viber, and Number Verifier service
         * @summary Get tariffs
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountTariffs: async (pageOffset?: number, pageLimit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/accounts/tariff`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageOffset !== undefined) {
                localVarQueryParameter['page[offset]'] = pageOffset;
            }

            if (pageLimit !== undefined) {
                localVarQueryParameter['page[limit]'] = pageLimit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BalanceApi - functional programming interface
 * @export
 */
export const BalanceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BalanceApiAxiosParamCreator(configuration)
    return {
        /**
         * Platform provides an API to get information about your account balance. The request allows you to obtain information about the current balance of your account, including the credit limit
         * @summary Get balance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountBalance(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountBalance200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountBalance(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BalanceApi.accountBalance']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This API allows you to get detailed information about the tariffs for sending SMS and Viber messages, as well as phone Number Verifier requests.  All rates are specified in the currency that is set in the account settings on the Platform.  The method transmits information about all available account tariffs for the SMS / 2 Way SMS, Viber, and Number Verifier service
         * @summary Get tariffs
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async accountTariffs(pageOffset?: number, pageLimit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AccountTariffs200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.accountTariffs(pageOffset, pageLimit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BalanceApi.accountTariffs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BalanceApi - factory interface
 * @export
 */
export const BalanceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BalanceApiFp(configuration)
    return {
        /**
         * Platform provides an API to get information about your account balance. The request allows you to obtain information about the current balance of your account, including the credit limit
         * @summary Get balance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountBalance(options?: RawAxiosRequestConfig): AxiosPromise<AccountBalance200Response> {
            return localVarFp.accountBalance(options).then((request) => request(axios, basePath));
        },
        /**
         * This API allows you to get detailed information about the tariffs for sending SMS and Viber messages, as well as phone Number Verifier requests.  All rates are specified in the currency that is set in the account settings on the Platform.  The method transmits information about all available account tariffs for the SMS / 2 Way SMS, Viber, and Number Verifier service
         * @summary Get tariffs
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        accountTariffs(pageOffset?: number, pageLimit?: number, options?: RawAxiosRequestConfig): AxiosPromise<AccountTariffs200Response> {
            return localVarFp.accountTariffs(pageOffset, pageLimit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BalanceApi - interface
 * @export
 * @interface BalanceApi
 */
export interface BalanceApiInterface {
    /**
     * Platform provides an API to get information about your account balance. The request allows you to obtain information about the current balance of your account, including the credit limit
     * @summary Get balance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BalanceApiInterface
     */
    accountBalance(options?: RawAxiosRequestConfig): AxiosPromise<AccountBalance200Response>;

    /**
     * This API allows you to get detailed information about the tariffs for sending SMS and Viber messages, as well as phone Number Verifier requests.  All rates are specified in the currency that is set in the account settings on the Platform.  The method transmits information about all available account tariffs for the SMS / 2 Way SMS, Viber, and Number Verifier service
     * @summary Get tariffs
     * @param {number} [pageOffset] 
     * @param {number} [pageLimit] The number of items in the response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BalanceApiInterface
     */
    accountTariffs(pageOffset?: number, pageLimit?: number, options?: RawAxiosRequestConfig): AxiosPromise<AccountTariffs200Response>;

}

/**
 * BalanceApi - object-oriented interface
 * @export
 * @class BalanceApi
 * @extends {BaseAPI}
 */
export class BalanceApi extends BaseAPI implements BalanceApiInterface {
    /**
     * Platform provides an API to get information about your account balance. The request allows you to obtain information about the current balance of your account, including the credit limit
     * @summary Get balance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BalanceApi
     */
    public accountBalance(options?: RawAxiosRequestConfig) {
        return BalanceApiFp(this.configuration).accountBalance(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This API allows you to get detailed information about the tariffs for sending SMS and Viber messages, as well as phone Number Verifier requests.  All rates are specified in the currency that is set in the account settings on the Platform.  The method transmits information about all available account tariffs for the SMS / 2 Way SMS, Viber, and Number Verifier service
     * @summary Get tariffs
     * @param {number} [pageOffset] 
     * @param {number} [pageLimit] The number of items in the response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BalanceApi
     */
    public accountTariffs(pageOffset?: number, pageLimit?: number, options?: RawAxiosRequestConfig) {
        return BalanceApiFp(this.configuration).accountTariffs(pageOffset, pageLimit, options).then((request) => request(this.axios, this.basePath));
    }
}

