/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SmsCampaignResponse } from '../models';
// @ts-ignore
import type { SmsSendGroupsRequest } from '../models';
// @ts-ignore
import type { SmsSendIndividualRequest } from '../models';
// @ts-ignore
import type { SmsSendRequest } from '../models';
// @ts-ignore
import type { TooManyRequestsResponse } from '../models';
/**
 * CampaignSMSApi - axios parameter creator
 * @export
 */
export const CampaignSMSApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * The method allows sending an SMS. The same text to list of phones will sent as single campaign
         * @summary Send SMS campaign
         * @param {SmsSendRequest} smsSendRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        smsSend: async (smsSendRequest: SmsSendRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'smsSendRequest' is not null or undefined
            assertParamExists('smsSend', 'smsSendRequest', smsSendRequest)
            const localVarPath = `/api/campaigns/sms/send`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(smsSendRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The method allows sending an SMS to the contacts list from the Contact Book. The campaign can contain personalized data from the contact fields in the text of the message for each contact.   It is possible to specify no more than 10 000 contacts for one campaign.  **Limitation:**   - In the DEMO account mode, creating a campaign via API is not available. - In the TEST platform mode, creating a campaign is possible only for the verified numbers.
         * @summary Send SMS to contact list
         * @param {SmsSendGroupsRequest} smsSendGroupsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        smsSendGroups: async (smsSendGroupsRequest: SmsSendGroupsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'smsSendGroupsRequest' is not null or undefined
            assertParamExists('smsSendGroups', 'smsSendGroupsRequest', smsSendGroupsRequest)
            const localVarPath = `/api/campaigns/sms/send-groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(smsSendGroupsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Send SMS with different text to list of phones
         * @summary Send SMS with different text
         * @param {SmsSendIndividualRequest} smsSendIndividualRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        smsSendIndividual: async (smsSendIndividualRequest: SmsSendIndividualRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'smsSendIndividualRequest' is not null or undefined
            assertParamExists('smsSendIndividual', 'smsSendIndividualRequest', smsSendIndividualRequest)
            const localVarPath = `/api/campaigns/sms/send-individual`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(smsSendIndividualRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CampaignSMSApi - functional programming interface
 * @export
 */
export const CampaignSMSApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CampaignSMSApiAxiosParamCreator(configuration)
    return {
        /**
         * The method allows sending an SMS. The same text to list of phones will sent as single campaign
         * @summary Send SMS campaign
         * @param {SmsSendRequest} smsSendRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async smsSend(smsSendRequest: SmsSendRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SmsCampaignResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.smsSend(smsSendRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CampaignSMSApi.smsSend']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The method allows sending an SMS to the contacts list from the Contact Book. The campaign can contain personalized data from the contact fields in the text of the message for each contact.   It is possible to specify no more than 10 000 contacts for one campaign.  **Limitation:**   - In the DEMO account mode, creating a campaign via API is not available. - In the TEST platform mode, creating a campaign is possible only for the verified numbers.
         * @summary Send SMS to contact list
         * @param {SmsSendGroupsRequest} smsSendGroupsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async smsSendGroups(smsSendGroupsRequest: SmsSendGroupsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SmsCampaignResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.smsSendGroups(smsSendGroupsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CampaignSMSApi.smsSendGroups']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Send SMS with different text to list of phones
         * @summary Send SMS with different text
         * @param {SmsSendIndividualRequest} smsSendIndividualRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async smsSendIndividual(smsSendIndividualRequest: SmsSendIndividualRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SmsCampaignResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.smsSendIndividual(smsSendIndividualRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CampaignSMSApi.smsSendIndividual']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CampaignSMSApi - factory interface
 * @export
 */
export const CampaignSMSApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CampaignSMSApiFp(configuration)
    return {
        /**
         * The method allows sending an SMS. The same text to list of phones will sent as single campaign
         * @summary Send SMS campaign
         * @param {SmsSendRequest} smsSendRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        smsSend(smsSendRequest: SmsSendRequest, options?: RawAxiosRequestConfig): AxiosPromise<SmsCampaignResponse> {
            return localVarFp.smsSend(smsSendRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * The method allows sending an SMS to the contacts list from the Contact Book. The campaign can contain personalized data from the contact fields in the text of the message for each contact.   It is possible to specify no more than 10 000 contacts for one campaign.  **Limitation:**   - In the DEMO account mode, creating a campaign via API is not available. - In the TEST platform mode, creating a campaign is possible only for the verified numbers.
         * @summary Send SMS to contact list
         * @param {SmsSendGroupsRequest} smsSendGroupsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        smsSendGroups(smsSendGroupsRequest: SmsSendGroupsRequest, options?: RawAxiosRequestConfig): AxiosPromise<SmsCampaignResponse> {
            return localVarFp.smsSendGroups(smsSendGroupsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Send SMS with different text to list of phones
         * @summary Send SMS with different text
         * @param {SmsSendIndividualRequest} smsSendIndividualRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        smsSendIndividual(smsSendIndividualRequest: SmsSendIndividualRequest, options?: RawAxiosRequestConfig): AxiosPromise<SmsCampaignResponse> {
            return localVarFp.smsSendIndividual(smsSendIndividualRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CampaignSMSApi - interface
 * @export
 * @interface CampaignSMSApi
 */
export interface CampaignSMSApiInterface {
    /**
     * The method allows sending an SMS. The same text to list of phones will sent as single campaign
     * @summary Send SMS campaign
     * @param {SmsSendRequest} smsSendRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignSMSApiInterface
     */
    smsSend(smsSendRequest: SmsSendRequest, options?: RawAxiosRequestConfig): AxiosPromise<SmsCampaignResponse>;

    /**
     * The method allows sending an SMS to the contacts list from the Contact Book. The campaign can contain personalized data from the contact fields in the text of the message for each contact.   It is possible to specify no more than 10 000 contacts for one campaign.  **Limitation:**   - In the DEMO account mode, creating a campaign via API is not available. - In the TEST platform mode, creating a campaign is possible only for the verified numbers.
     * @summary Send SMS to contact list
     * @param {SmsSendGroupsRequest} smsSendGroupsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignSMSApiInterface
     */
    smsSendGroups(smsSendGroupsRequest: SmsSendGroupsRequest, options?: RawAxiosRequestConfig): AxiosPromise<SmsCampaignResponse>;

    /**
     * Send SMS with different text to list of phones
     * @summary Send SMS with different text
     * @param {SmsSendIndividualRequest} smsSendIndividualRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignSMSApiInterface
     */
    smsSendIndividual(smsSendIndividualRequest: SmsSendIndividualRequest, options?: RawAxiosRequestConfig): AxiosPromise<SmsCampaignResponse>;

}

/**
 * CampaignSMSApi - object-oriented interface
 * @export
 * @class CampaignSMSApi
 * @extends {BaseAPI}
 */
export class CampaignSMSApi extends BaseAPI implements CampaignSMSApiInterface {
    /**
     * The method allows sending an SMS. The same text to list of phones will sent as single campaign
     * @summary Send SMS campaign
     * @param {SmsSendRequest} smsSendRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignSMSApi
     */
    public smsSend(smsSendRequest: SmsSendRequest, options?: RawAxiosRequestConfig) {
        return CampaignSMSApiFp(this.configuration).smsSend(smsSendRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The method allows sending an SMS to the contacts list from the Contact Book. The campaign can contain personalized data from the contact fields in the text of the message for each contact.   It is possible to specify no more than 10 000 contacts for one campaign.  **Limitation:**   - In the DEMO account mode, creating a campaign via API is not available. - In the TEST platform mode, creating a campaign is possible only for the verified numbers.
     * @summary Send SMS to contact list
     * @param {SmsSendGroupsRequest} smsSendGroupsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignSMSApi
     */
    public smsSendGroups(smsSendGroupsRequest: SmsSendGroupsRequest, options?: RawAxiosRequestConfig) {
        return CampaignSMSApiFp(this.configuration).smsSendGroups(smsSendGroupsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Send SMS with different text to list of phones
     * @summary Send SMS with different text
     * @param {SmsSendIndividualRequest} smsSendIndividualRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignSMSApi
     */
    public smsSendIndividual(smsSendIndividualRequest: SmsSendIndividualRequest, options?: RawAxiosRequestConfig) {
        return CampaignSMSApiFp(this.configuration).smsSendIndividual(smsSendIndividualRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

