/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CampaignSchema } from '../models';
// @ts-ignore
import type { SendWhatsAppCampaign } from '../models';
/**
 * CampaignWhatsAppApi - axios parameter creator
 * @export
 */
export const CampaignWhatsAppApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This method allows you to send a whatsapp. The same message will be sent to list of phones
         * @summary Send WhatsApp campaign
         * @param {SendWhatsAppCampaign} sendWhatsAppCampaign 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postCampaignsWhatsappSend: async (sendWhatsAppCampaign: SendWhatsAppCampaign, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sendWhatsAppCampaign' is not null or undefined
            assertParamExists('postCampaignsWhatsappSend', 'sendWhatsAppCampaign', sendWhatsAppCampaign)
            const localVarPath = `/api/campaigns/whatsapp/send`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendWhatsAppCampaign, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CampaignWhatsAppApi - functional programming interface
 * @export
 */
export const CampaignWhatsAppApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CampaignWhatsAppApiAxiosParamCreator(configuration)
    return {
        /**
         * This method allows you to send a whatsapp. The same message will be sent to list of phones
         * @summary Send WhatsApp campaign
         * @param {SendWhatsAppCampaign} sendWhatsAppCampaign 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postCampaignsWhatsappSend(sendWhatsAppCampaign: SendWhatsAppCampaign, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CampaignSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postCampaignsWhatsappSend(sendWhatsAppCampaign, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CampaignWhatsAppApi.postCampaignsWhatsappSend']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CampaignWhatsAppApi - factory interface
 * @export
 */
export const CampaignWhatsAppApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CampaignWhatsAppApiFp(configuration)
    return {
        /**
         * This method allows you to send a whatsapp. The same message will be sent to list of phones
         * @summary Send WhatsApp campaign
         * @param {SendWhatsAppCampaign} sendWhatsAppCampaign 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postCampaignsWhatsappSend(sendWhatsAppCampaign: SendWhatsAppCampaign, options?: RawAxiosRequestConfig): AxiosPromise<CampaignSchema> {
            return localVarFp.postCampaignsWhatsappSend(sendWhatsAppCampaign, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CampaignWhatsAppApi - interface
 * @export
 * @interface CampaignWhatsAppApi
 */
export interface CampaignWhatsAppApiInterface {
    /**
     * This method allows you to send a whatsapp. The same message will be sent to list of phones
     * @summary Send WhatsApp campaign
     * @param {SendWhatsAppCampaign} sendWhatsAppCampaign 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignWhatsAppApiInterface
     */
    postCampaignsWhatsappSend(sendWhatsAppCampaign: SendWhatsAppCampaign, options?: RawAxiosRequestConfig): AxiosPromise<CampaignSchema>;

}

/**
 * CampaignWhatsAppApi - object-oriented interface
 * @export
 * @class CampaignWhatsAppApi
 * @extends {BaseAPI}
 */
export class CampaignWhatsAppApi extends BaseAPI implements CampaignWhatsAppApiInterface {
    /**
     * This method allows you to send a whatsapp. The same message will be sent to list of phones
     * @summary Send WhatsApp campaign
     * @param {SendWhatsAppCampaign} sendWhatsAppCampaign 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CampaignWhatsAppApi
     */
    public postCampaignsWhatsappSend(sendWhatsAppCampaign: SendWhatsAppCampaign, options?: RawAxiosRequestConfig) {
        return CampaignWhatsAppApiFp(this.configuration).postCampaignsWhatsappSend(sendWhatsAppCampaign, options).then((request) => request(this.axios, this.basePath));
    }
}

