/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ContactFieldCollectionSchema } from '../models';
// @ts-ignore
import type { ContactFieldCreate201Response } from '../models';
// @ts-ignore
import type { ContactFieldCreateRequest } from '../models';
// @ts-ignore
import type { ContactFieldUpdate200Response } from '../models';
// @ts-ignore
import type { ContactFieldUpdateRequest } from '../models';
// @ts-ignore
import type { PostContactsFieldsDeleteRequest } from '../models';
// @ts-ignore
import type { TooManyRequestsResponse } from '../models';
/**
 * ContactFieldApi - axios parameter creator
 * @export
 */
export const ContactFieldApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * The method allows the creation of additional custom fields for contacts
         * @summary Create contact field
         * @param {ContactFieldCreateRequest} contactFieldCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactFieldCreate: async (contactFieldCreateRequest: ContactFieldCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactFieldCreateRequest' is not null or undefined
            assertParamExists('contactFieldCreate', 'contactFieldCreateRequest', contactFieldCreateRequest)
            const localVarPath = `/api/contacts/fields`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contactFieldCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Method for editing custom contact field:  - change field name - change field description 
         * @summary Update contact field
         * @param {number} id Contact field id
         * @param {ContactFieldUpdateRequest} contactFieldUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactFieldUpdate: async (id: number, contactFieldUpdateRequest: ContactFieldUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contactFieldUpdate', 'id', id)
            // verify required parameter 'contactFieldUpdateRequest' is not null or undefined
            assertParamExists('contactFieldUpdate', 'contactFieldUpdateRequest', contactFieldUpdateRequest)
            const localVarPath = `/api/contacts/fields/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contactFieldUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a list of custom fields
         * @summary List of contact fields
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactFields: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/contacts/fields`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete multiple (up to 30) contact fields
         * @summary Delete contact fields by ids
         * @param {PostContactsFieldsDeleteRequest} postContactsFieldsDeleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postContactsFieldsDelete: async (postContactsFieldsDeleteRequest: PostContactsFieldsDeleteRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postContactsFieldsDeleteRequest' is not null or undefined
            assertParamExists('postContactsFieldsDelete', 'postContactsFieldsDeleteRequest', postContactsFieldsDeleteRequest)
            const localVarPath = `/api/contacts/fields/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postContactsFieldsDeleteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ContactFieldApi - functional programming interface
 * @export
 */
export const ContactFieldApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ContactFieldApiAxiosParamCreator(configuration)
    return {
        /**
         * The method allows the creation of additional custom fields for contacts
         * @summary Create contact field
         * @param {ContactFieldCreateRequest} contactFieldCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactFieldCreate(contactFieldCreateRequest: ContactFieldCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactFieldCreate201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactFieldCreate(contactFieldCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactFieldApi.contactFieldCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Method for editing custom contact field:  - change field name - change field description 
         * @summary Update contact field
         * @param {number} id Contact field id
         * @param {ContactFieldUpdateRequest} contactFieldUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactFieldUpdate(id: number, contactFieldUpdateRequest: ContactFieldUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactFieldUpdate200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactFieldUpdate(id, contactFieldUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactFieldApi.contactFieldUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get a list of custom fields
         * @summary List of contact fields
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactFields(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactFieldCollectionSchema>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactFields(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactFieldApi.contactFields']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete multiple (up to 30) contact fields
         * @summary Delete contact fields by ids
         * @param {PostContactsFieldsDeleteRequest} postContactsFieldsDeleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postContactsFieldsDelete(postContactsFieldsDeleteRequest: PostContactsFieldsDeleteRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postContactsFieldsDelete(postContactsFieldsDeleteRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactFieldApi.postContactsFieldsDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ContactFieldApi - factory interface
 * @export
 */
export const ContactFieldApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ContactFieldApiFp(configuration)
    return {
        /**
         * The method allows the creation of additional custom fields for contacts
         * @summary Create contact field
         * @param {ContactFieldCreateRequest} contactFieldCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactFieldCreate(contactFieldCreateRequest: ContactFieldCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactFieldCreate201Response> {
            return localVarFp.contactFieldCreate(contactFieldCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Method for editing custom contact field:  - change field name - change field description 
         * @summary Update contact field
         * @param {number} id Contact field id
         * @param {ContactFieldUpdateRequest} contactFieldUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactFieldUpdate(id: number, contactFieldUpdateRequest: ContactFieldUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactFieldUpdate200Response> {
            return localVarFp.contactFieldUpdate(id, contactFieldUpdateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a list of custom fields
         * @summary List of contact fields
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactFields(options?: RawAxiosRequestConfig): AxiosPromise<ContactFieldCollectionSchema> {
            return localVarFp.contactFields(options).then((request) => request(axios, basePath));
        },
        /**
         * Delete multiple (up to 30) contact fields
         * @summary Delete contact fields by ids
         * @param {PostContactsFieldsDeleteRequest} postContactsFieldsDeleteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postContactsFieldsDelete(postContactsFieldsDeleteRequest: PostContactsFieldsDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.postContactsFieldsDelete(postContactsFieldsDeleteRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ContactFieldApi - interface
 * @export
 * @interface ContactFieldApi
 */
export interface ContactFieldApiInterface {
    /**
     * The method allows the creation of additional custom fields for contacts
     * @summary Create contact field
     * @param {ContactFieldCreateRequest} contactFieldCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactFieldApiInterface
     */
    contactFieldCreate(contactFieldCreateRequest: ContactFieldCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactFieldCreate201Response>;

    /**
     * Method for editing custom contact field:  - change field name - change field description 
     * @summary Update contact field
     * @param {number} id Contact field id
     * @param {ContactFieldUpdateRequest} contactFieldUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactFieldApiInterface
     */
    contactFieldUpdate(id: number, contactFieldUpdateRequest: ContactFieldUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactFieldUpdate200Response>;

    /**
     * Get a list of custom fields
     * @summary List of contact fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactFieldApiInterface
     */
    contactFields(options?: RawAxiosRequestConfig): AxiosPromise<ContactFieldCollectionSchema>;

    /**
     * Delete multiple (up to 30) contact fields
     * @summary Delete contact fields by ids
     * @param {PostContactsFieldsDeleteRequest} postContactsFieldsDeleteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactFieldApiInterface
     */
    postContactsFieldsDelete(postContactsFieldsDeleteRequest: PostContactsFieldsDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<object>;

}

/**
 * ContactFieldApi - object-oriented interface
 * @export
 * @class ContactFieldApi
 * @extends {BaseAPI}
 */
export class ContactFieldApi extends BaseAPI implements ContactFieldApiInterface {
    /**
     * The method allows the creation of additional custom fields for contacts
     * @summary Create contact field
     * @param {ContactFieldCreateRequest} contactFieldCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactFieldApi
     */
    public contactFieldCreate(contactFieldCreateRequest: ContactFieldCreateRequest, options?: RawAxiosRequestConfig) {
        return ContactFieldApiFp(this.configuration).contactFieldCreate(contactFieldCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Method for editing custom contact field:  - change field name - change field description 
     * @summary Update contact field
     * @param {number} id Contact field id
     * @param {ContactFieldUpdateRequest} contactFieldUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactFieldApi
     */
    public contactFieldUpdate(id: number, contactFieldUpdateRequest: ContactFieldUpdateRequest, options?: RawAxiosRequestConfig) {
        return ContactFieldApiFp(this.configuration).contactFieldUpdate(id, contactFieldUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a list of custom fields
     * @summary List of contact fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactFieldApi
     */
    public contactFields(options?: RawAxiosRequestConfig) {
        return ContactFieldApiFp(this.configuration).contactFields(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete multiple (up to 30) contact fields
     * @summary Delete contact fields by ids
     * @param {PostContactsFieldsDeleteRequest} postContactsFieldsDeleteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactFieldApi
     */
    public postContactsFieldsDelete(postContactsFieldsDeleteRequest: PostContactsFieldsDeleteRequest, options?: RawAxiosRequestConfig) {
        return ContactFieldApiFp(this.configuration).postContactsFieldsDelete(postContactsFieldsDeleteRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

