/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Contact200Response } from '../models';
// @ts-ignore
import type { Contact422Response } from '../models';
// @ts-ignore
import type { ContactCreate201Response } from '../models';
// @ts-ignore
import type { ContactCreate422Response } from '../models';
// @ts-ignore
import type { ContactUpdate200Response } from '../models';
// @ts-ignore
import type { ContactUpdate422Response } from '../models';
// @ts-ignore
import type { ContactUpdateRequest } from '../models';
// @ts-ignore
import type { Contacts200Response } from '../models';
// @ts-ignore
import type { ContactsSearch200Response } from '../models';
// @ts-ignore
import type { SearchOperator } from '../models';
// @ts-ignore
import type { SortWay } from '../models';
// @ts-ignore
import type { StoreContact } from '../models';
// @ts-ignore
import type { TooManyRequestsResponse } from '../models';
/**
 * ContactApi - axios parameter creator
 * @export
 */
export const ContactApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * The method allows you to receive detailed information about an existing contact, which is contained in the system, and user fields of the contact
         * @summary Get contact by ID
         * @param {number} id Contact id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contact: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contact', 'id', id)
            const localVarPath = `/api/contacts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The method allows adding new contacts to your Contact Book.   **Please note:** that in the TEST account mode there is a restriction for performing this method: it is possible to create a contact only for a verified phone number (number verification is performed in the personal account of the platform).
         * @summary Create a contact
         * @param {StoreContact} storeContact 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactCreate: async (storeContact: StoreContact, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'storeContact' is not null or undefined
            assertParamExists('contactCreate', 'storeContact', storeContact)
            const localVarPath = `/api/contacts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(storeContact, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this query to remove an existing contact from the Contact Book. When this query is made, the contact will also be removed from all lists where it was added.
         * @summary Delete contact
         * @param {number} id Contact id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contactDelete', 'id', id)
            const localVarPath = `/api/contacts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The method allows you to make changes to an existing contact: change the phone number, data in the contact’s custom fields, and add the contact to the list.  **Please note:** that in the TEST account mode there is a restriction for performing this method: you can only change the contact’s phone number to a verified number (number verification is performed in the personal account at the platform)
         * @summary Update contact
         * @param {number} id Contact id
         * @param {ContactUpdateRequest} contactUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactUpdate: async (id: number, contactUpdateRequest: ContactUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contactUpdate', 'id', id)
            // verify required parameter 'contactUpdateRequest' is not null or undefined
            assertParamExists('contactUpdate', 'contactUpdateRequest', contactUpdateRequest)
            const localVarPath = `/api/contacts/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contactUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a list of existing contacts in the Contact Book of your account with detailed information on each of them. The method also allows you to get contacts from the certain lists that you specified in the query parameters.
         * @summary List of contacts
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {Array<number>} [groups] Index of IDs of the lists for which you want to display contacts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contacts: async (pageOffset?: number, pageLimit?: number, groups?: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/contacts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageOffset !== undefined) {
                localVarQueryParameter['page[offset]'] = pageOffset;
            }

            if (pageLimit !== undefined) {
                localVarQueryParameter['page[limit]'] = pageLimit;
            }

            if (groups) {
                localVarQueryParameter['groups[]'] = groups;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Method allow to delete multiple contacts (up to 5000) for a single request  It may be list of contact ids to delete or list of contact lists ids to delete **contacts** included into these lists. 
         * @summary Delete multiple contacts
         * @param {Array<number>} [contactIds] Contact ids to delete
         * @param {Array<number>} [groupIds] Contact lists ids to delete **contacts** included into these lists
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactsDelete: async (contactIds?: Array<number>, groupIds?: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/contacts/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (contactIds) {
                localVarQueryParameter['contact_ids[]'] = contactIds;
            }

            if (groupIds) {
                localVarQueryParameter['group_ids[]'] = groupIds;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Method for searching contacts in the Contact Book. In the search, it is possible to use operations: like, =, >, >=, <, <=.  Search is possible by the following fields:   - id:  =, >, >=, <, <= - phone: like, = - {field_id}:   - for field with \"Text\" type: like, =   - for field with \"Number\" type:  =, >, >=, <, <=   - for field with \"Date\" type: =, >, >=, <, <=  It’s possible to pass multiple criteria by pass `search_fields` array instead of `search` 
         * @summary Search contacts
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {ContactsSearchSortEnum} [sort] Sort by conditions: id, phone
         * @param {SortWay} [way] 
         * @param {string} [searchField] 
         * @param {SearchOperator} [searchOperator] 
         * @param {string} [searchValue] 
         * @param {string} [searchFields0Field] 
         * @param {SearchOperator} [searchFields0Operator] 
         * @param {string} [searchFields0Value] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactsSearch: async (pageOffset?: number, pageLimit?: number, sort?: ContactsSearchSortEnum, way?: SortWay, searchField?: string, searchOperator?: SearchOperator, searchValue?: string, searchFields0Field?: string, searchFields0Operator?: SearchOperator, searchFields0Value?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/contacts/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageOffset !== undefined) {
                localVarQueryParameter['page[offset]'] = pageOffset;
            }

            if (pageLimit !== undefined) {
                localVarQueryParameter['page[limit]'] = pageLimit;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (way !== undefined) {
                localVarQueryParameter['way'] = way;
            }

            if (searchField !== undefined) {
                localVarQueryParameter['search[field]'] = searchField;
            }

            if (searchOperator !== undefined) {
                localVarQueryParameter['search[operator]'] = searchOperator;
            }

            if (searchValue !== undefined) {
                localVarQueryParameter['search[value]'] = searchValue;
            }

            if (searchFields0Field !== undefined) {
                localVarQueryParameter['search_fields[0][field]'] = searchFields0Field;
            }

            if (searchFields0Operator !== undefined) {
                localVarQueryParameter['search_fields[0][operator]'] = searchFields0Operator;
            }

            if (searchFields0Value !== undefined) {
                localVarQueryParameter['search_fields[0][value]'] = searchFields0Value;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ContactApi - functional programming interface
 * @export
 */
export const ContactApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ContactApiAxiosParamCreator(configuration)
    return {
        /**
         * The method allows you to receive detailed information about an existing contact, which is contained in the system, and user fields of the contact
         * @summary Get contact by ID
         * @param {number} id Contact id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contact(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Contact200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contact(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactApi.contact']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The method allows adding new contacts to your Contact Book.   **Please note:** that in the TEST account mode there is a restriction for performing this method: it is possible to create a contact only for a verified phone number (number verification is performed in the personal account of the platform).
         * @summary Create a contact
         * @param {StoreContact} storeContact 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactCreate(storeContact: StoreContact, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactCreate201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactCreate(storeContact, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactApi.contactCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Use this query to remove an existing contact from the Contact Book. When this query is made, the contact will also be removed from all lists where it was added.
         * @summary Delete contact
         * @param {number} id Contact id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactApi.contactDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The method allows you to make changes to an existing contact: change the phone number, data in the contact’s custom fields, and add the contact to the list.  **Please note:** that in the TEST account mode there is a restriction for performing this method: you can only change the contact’s phone number to a verified number (number verification is performed in the personal account at the platform)
         * @summary Update contact
         * @param {number} id Contact id
         * @param {ContactUpdateRequest} contactUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactUpdate(id: number, contactUpdateRequest: ContactUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactUpdate200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactUpdate(id, contactUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactApi.contactUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get a list of existing contacts in the Contact Book of your account with detailed information on each of them. The method also allows you to get contacts from the certain lists that you specified in the query parameters.
         * @summary List of contacts
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {Array<number>} [groups] Index of IDs of the lists for which you want to display contacts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contacts(pageOffset?: number, pageLimit?: number, groups?: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Contacts200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contacts(pageOffset, pageLimit, groups, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactApi.contacts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Method allow to delete multiple contacts (up to 5000) for a single request  It may be list of contact ids to delete or list of contact lists ids to delete **contacts** included into these lists. 
         * @summary Delete multiple contacts
         * @param {Array<number>} [contactIds] Contact ids to delete
         * @param {Array<number>} [groupIds] Contact lists ids to delete **contacts** included into these lists
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactsDelete(contactIds?: Array<number>, groupIds?: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactsDelete(contactIds, groupIds, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactApi.contactsDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Method for searching contacts in the Contact Book. In the search, it is possible to use operations: like, =, >, >=, <, <=.  Search is possible by the following fields:   - id:  =, >, >=, <, <= - phone: like, = - {field_id}:   - for field with \"Text\" type: like, =   - for field with \"Number\" type:  =, >, >=, <, <=   - for field with \"Date\" type: =, >, >=, <, <=  It’s possible to pass multiple criteria by pass `search_fields` array instead of `search` 
         * @summary Search contacts
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {ContactsSearchSortEnum} [sort] Sort by conditions: id, phone
         * @param {SortWay} [way] 
         * @param {string} [searchField] 
         * @param {SearchOperator} [searchOperator] 
         * @param {string} [searchValue] 
         * @param {string} [searchFields0Field] 
         * @param {SearchOperator} [searchFields0Operator] 
         * @param {string} [searchFields0Value] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactsSearch(pageOffset?: number, pageLimit?: number, sort?: ContactsSearchSortEnum, way?: SortWay, searchField?: string, searchOperator?: SearchOperator, searchValue?: string, searchFields0Field?: string, searchFields0Operator?: SearchOperator, searchFields0Value?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactsSearch200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactsSearch(pageOffset, pageLimit, sort, way, searchField, searchOperator, searchValue, searchFields0Field, searchFields0Operator, searchFields0Value, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactApi.contactsSearch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ContactApi - factory interface
 * @export
 */
export const ContactApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ContactApiFp(configuration)
    return {
        /**
         * The method allows you to receive detailed information about an existing contact, which is contained in the system, and user fields of the contact
         * @summary Get contact by ID
         * @param {number} id Contact id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contact(id: number, options?: RawAxiosRequestConfig): AxiosPromise<Contact200Response> {
            return localVarFp.contact(id, options).then((request) => request(axios, basePath));
        },
        /**
         * The method allows adding new contacts to your Contact Book.   **Please note:** that in the TEST account mode there is a restriction for performing this method: it is possible to create a contact only for a verified phone number (number verification is performed in the personal account of the platform).
         * @summary Create a contact
         * @param {StoreContact} storeContact 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactCreate(storeContact: StoreContact, options?: RawAxiosRequestConfig): AxiosPromise<ContactCreate201Response> {
            return localVarFp.contactCreate(storeContact, options).then((request) => request(axios, basePath));
        },
        /**
         * Use this query to remove an existing contact from the Contact Book. When this query is made, the contact will also be removed from all lists where it was added.
         * @summary Delete contact
         * @param {number} id Contact id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactDelete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.contactDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * The method allows you to make changes to an existing contact: change the phone number, data in the contact’s custom fields, and add the contact to the list.  **Please note:** that in the TEST account mode there is a restriction for performing this method: you can only change the contact’s phone number to a verified number (number verification is performed in the personal account at the platform)
         * @summary Update contact
         * @param {number} id Contact id
         * @param {ContactUpdateRequest} contactUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactUpdate(id: number, contactUpdateRequest: ContactUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactUpdate200Response> {
            return localVarFp.contactUpdate(id, contactUpdateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a list of existing contacts in the Contact Book of your account with detailed information on each of them. The method also allows you to get contacts from the certain lists that you specified in the query parameters.
         * @summary List of contacts
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {Array<number>} [groups] Index of IDs of the lists for which you want to display contacts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contacts(pageOffset?: number, pageLimit?: number, groups?: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<Contacts200Response> {
            return localVarFp.contacts(pageOffset, pageLimit, groups, options).then((request) => request(axios, basePath));
        },
        /**
         * Method allow to delete multiple contacts (up to 5000) for a single request  It may be list of contact ids to delete or list of contact lists ids to delete **contacts** included into these lists. 
         * @summary Delete multiple contacts
         * @param {Array<number>} [contactIds] Contact ids to delete
         * @param {Array<number>} [groupIds] Contact lists ids to delete **contacts** included into these lists
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactsDelete(contactIds?: Array<number>, groupIds?: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.contactsDelete(contactIds, groupIds, options).then((request) => request(axios, basePath));
        },
        /**
         * Method for searching contacts in the Contact Book. In the search, it is possible to use operations: like, =, >, >=, <, <=.  Search is possible by the following fields:   - id:  =, >, >=, <, <= - phone: like, = - {field_id}:   - for field with \"Text\" type: like, =   - for field with \"Number\" type:  =, >, >=, <, <=   - for field with \"Date\" type: =, >, >=, <, <=  It’s possible to pass multiple criteria by pass `search_fields` array instead of `search` 
         * @summary Search contacts
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {ContactsSearchSortEnum} [sort] Sort by conditions: id, phone
         * @param {SortWay} [way] 
         * @param {string} [searchField] 
         * @param {SearchOperator} [searchOperator] 
         * @param {string} [searchValue] 
         * @param {string} [searchFields0Field] 
         * @param {SearchOperator} [searchFields0Operator] 
         * @param {string} [searchFields0Value] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactsSearch(pageOffset?: number, pageLimit?: number, sort?: ContactsSearchSortEnum, way?: SortWay, searchField?: string, searchOperator?: SearchOperator, searchValue?: string, searchFields0Field?: string, searchFields0Operator?: SearchOperator, searchFields0Value?: string, options?: RawAxiosRequestConfig): AxiosPromise<ContactsSearch200Response> {
            return localVarFp.contactsSearch(pageOffset, pageLimit, sort, way, searchField, searchOperator, searchValue, searchFields0Field, searchFields0Operator, searchFields0Value, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ContactApi - interface
 * @export
 * @interface ContactApi
 */
export interface ContactApiInterface {
    /**
     * The method allows you to receive detailed information about an existing contact, which is contained in the system, and user fields of the contact
     * @summary Get contact by ID
     * @param {number} id Contact id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApiInterface
     */
    contact(id: number, options?: RawAxiosRequestConfig): AxiosPromise<Contact200Response>;

    /**
     * The method allows adding new contacts to your Contact Book.   **Please note:** that in the TEST account mode there is a restriction for performing this method: it is possible to create a contact only for a verified phone number (number verification is performed in the personal account of the platform).
     * @summary Create a contact
     * @param {StoreContact} storeContact 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApiInterface
     */
    contactCreate(storeContact: StoreContact, options?: RawAxiosRequestConfig): AxiosPromise<ContactCreate201Response>;

    /**
     * Use this query to remove an existing contact from the Contact Book. When this query is made, the contact will also be removed from all lists where it was added.
     * @summary Delete contact
     * @param {number} id Contact id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApiInterface
     */
    contactDelete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<object>;

    /**
     * The method allows you to make changes to an existing contact: change the phone number, data in the contact’s custom fields, and add the contact to the list.  **Please note:** that in the TEST account mode there is a restriction for performing this method: you can only change the contact’s phone number to a verified number (number verification is performed in the personal account at the platform)
     * @summary Update contact
     * @param {number} id Contact id
     * @param {ContactUpdateRequest} contactUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApiInterface
     */
    contactUpdate(id: number, contactUpdateRequest: ContactUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactUpdate200Response>;

    /**
     * Get a list of existing contacts in the Contact Book of your account with detailed information on each of them. The method also allows you to get contacts from the certain lists that you specified in the query parameters.
     * @summary List of contacts
     * @param {number} [pageOffset] 
     * @param {number} [pageLimit] The number of items in the response
     * @param {Array<number>} [groups] Index of IDs of the lists for which you want to display contacts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApiInterface
     */
    contacts(pageOffset?: number, pageLimit?: number, groups?: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<Contacts200Response>;

    /**
     * Method allow to delete multiple contacts (up to 5000) for a single request  It may be list of contact ids to delete or list of contact lists ids to delete **contacts** included into these lists. 
     * @summary Delete multiple contacts
     * @param {Array<number>} [contactIds] Contact ids to delete
     * @param {Array<number>} [groupIds] Contact lists ids to delete **contacts** included into these lists
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApiInterface
     */
    contactsDelete(contactIds?: Array<number>, groupIds?: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<object>;

    /**
     * Method for searching contacts in the Contact Book. In the search, it is possible to use operations: like, =, >, >=, <, <=.  Search is possible by the following fields:   - id:  =, >, >=, <, <= - phone: like, = - {field_id}:   - for field with \"Text\" type: like, =   - for field with \"Number\" type:  =, >, >=, <, <=   - for field with \"Date\" type: =, >, >=, <, <=  It’s possible to pass multiple criteria by pass `search_fields` array instead of `search` 
     * @summary Search contacts
     * @param {number} [pageOffset] 
     * @param {number} [pageLimit] The number of items in the response
     * @param {ContactsSearchSortEnum} [sort] Sort by conditions: id, phone
     * @param {SortWay} [way] 
     * @param {string} [searchField] 
     * @param {SearchOperator} [searchOperator] 
     * @param {string} [searchValue] 
     * @param {string} [searchFields0Field] 
     * @param {SearchOperator} [searchFields0Operator] 
     * @param {string} [searchFields0Value] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApiInterface
     */
    contactsSearch(pageOffset?: number, pageLimit?: number, sort?: ContactsSearchSortEnum, way?: SortWay, searchField?: string, searchOperator?: SearchOperator, searchValue?: string, searchFields0Field?: string, searchFields0Operator?: SearchOperator, searchFields0Value?: string, options?: RawAxiosRequestConfig): AxiosPromise<ContactsSearch200Response>;

}

/**
 * ContactApi - object-oriented interface
 * @export
 * @class ContactApi
 * @extends {BaseAPI}
 */
export class ContactApi extends BaseAPI implements ContactApiInterface {
    /**
     * The method allows you to receive detailed information about an existing contact, which is contained in the system, and user fields of the contact
     * @summary Get contact by ID
     * @param {number} id Contact id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApi
     */
    public contact(id: number, options?: RawAxiosRequestConfig) {
        return ContactApiFp(this.configuration).contact(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The method allows adding new contacts to your Contact Book.   **Please note:** that in the TEST account mode there is a restriction for performing this method: it is possible to create a contact only for a verified phone number (number verification is performed in the personal account of the platform).
     * @summary Create a contact
     * @param {StoreContact} storeContact 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApi
     */
    public contactCreate(storeContact: StoreContact, options?: RawAxiosRequestConfig) {
        return ContactApiFp(this.configuration).contactCreate(storeContact, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this query to remove an existing contact from the Contact Book. When this query is made, the contact will also be removed from all lists where it was added.
     * @summary Delete contact
     * @param {number} id Contact id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApi
     */
    public contactDelete(id: number, options?: RawAxiosRequestConfig) {
        return ContactApiFp(this.configuration).contactDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The method allows you to make changes to an existing contact: change the phone number, data in the contact’s custom fields, and add the contact to the list.  **Please note:** that in the TEST account mode there is a restriction for performing this method: you can only change the contact’s phone number to a verified number (number verification is performed in the personal account at the platform)
     * @summary Update contact
     * @param {number} id Contact id
     * @param {ContactUpdateRequest} contactUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApi
     */
    public contactUpdate(id: number, contactUpdateRequest: ContactUpdateRequest, options?: RawAxiosRequestConfig) {
        return ContactApiFp(this.configuration).contactUpdate(id, contactUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a list of existing contacts in the Contact Book of your account with detailed information on each of them. The method also allows you to get contacts from the certain lists that you specified in the query parameters.
     * @summary List of contacts
     * @param {number} [pageOffset] 
     * @param {number} [pageLimit] The number of items in the response
     * @param {Array<number>} [groups] Index of IDs of the lists for which you want to display contacts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApi
     */
    public contacts(pageOffset?: number, pageLimit?: number, groups?: Array<number>, options?: RawAxiosRequestConfig) {
        return ContactApiFp(this.configuration).contacts(pageOffset, pageLimit, groups, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Method allow to delete multiple contacts (up to 5000) for a single request  It may be list of contact ids to delete or list of contact lists ids to delete **contacts** included into these lists. 
     * @summary Delete multiple contacts
     * @param {Array<number>} [contactIds] Contact ids to delete
     * @param {Array<number>} [groupIds] Contact lists ids to delete **contacts** included into these lists
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApi
     */
    public contactsDelete(contactIds?: Array<number>, groupIds?: Array<number>, options?: RawAxiosRequestConfig) {
        return ContactApiFp(this.configuration).contactsDelete(contactIds, groupIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Method for searching contacts in the Contact Book. In the search, it is possible to use operations: like, =, >, >=, <, <=.  Search is possible by the following fields:   - id:  =, >, >=, <, <= - phone: like, = - {field_id}:   - for field with \"Text\" type: like, =   - for field with \"Number\" type:  =, >, >=, <, <=   - for field with \"Date\" type: =, >, >=, <, <=  It’s possible to pass multiple criteria by pass `search_fields` array instead of `search` 
     * @summary Search contacts
     * @param {number} [pageOffset] 
     * @param {number} [pageLimit] The number of items in the response
     * @param {ContactsSearchSortEnum} [sort] Sort by conditions: id, phone
     * @param {SortWay} [way] 
     * @param {string} [searchField] 
     * @param {SearchOperator} [searchOperator] 
     * @param {string} [searchValue] 
     * @param {string} [searchFields0Field] 
     * @param {SearchOperator} [searchFields0Operator] 
     * @param {string} [searchFields0Value] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactApi
     */
    public contactsSearch(pageOffset?: number, pageLimit?: number, sort?: ContactsSearchSortEnum, way?: SortWay, searchField?: string, searchOperator?: SearchOperator, searchValue?: string, searchFields0Field?: string, searchFields0Operator?: SearchOperator, searchFields0Value?: string, options?: RawAxiosRequestConfig) {
        return ContactApiFp(this.configuration).contactsSearch(pageOffset, pageLimit, sort, way, searchField, searchOperator, searchValue, searchFields0Field, searchFields0Operator, searchFields0Value, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const ContactsSearchSortEnum = {
    Id: 'id',
    Phone: 'phone'
} as const;
export type ContactsSearchSortEnum = typeof ContactsSearchSortEnum[keyof typeof ContactsSearchSortEnum];
