/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ContactGroupSearchField } from '../models';
// @ts-ignore
import type { ContactList200Response } from '../models';
// @ts-ignore
import type { ContactListAttachRequest } from '../models';
// @ts-ignore
import type { ContactListCreate201Response } from '../models';
// @ts-ignore
import type { ContactListCreate422Response } from '../models';
// @ts-ignore
import type { ContactListCreateRequest } from '../models';
// @ts-ignore
import type { ContactListDetachRequest } from '../models';
// @ts-ignore
import type { ContactListSearch200Response } from '../models';
// @ts-ignore
import type { ContactListUpdate200Response } from '../models';
// @ts-ignore
import type { ContactListUpdate422Response } from '../models';
// @ts-ignore
import type { ContactListUpdateRequest } from '../models';
// @ts-ignore
import type { ContactLists200Response } from '../models';
// @ts-ignore
import type { SearchOperator } from '../models';
// @ts-ignore
import type { SortWay } from '../models';
// @ts-ignore
import type { TooManyRequestsResponse } from '../models';
/**
 * ContactListApi - axios parameter creator
 * @export
 */
export const ContactListApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get information about the contact list by its identifier
         * @summary Get list by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactList: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contactList', 'id', id)
            const localVarPath = `/api/groups/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The method provides the ability to add an existing contact to the list. The action can be single or bulk.
         * @summary Add contacts to the list
         * @param {ContactListAttachRequest} contactListAttachRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactListAttach: async (contactListAttachRequest: ContactListAttachRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactListAttachRequest' is not null or undefined
            assertParamExists('contactListAttach', 'contactListAttachRequest', contactListAttachRequest)
            const localVarPath = `/api/groups/attach`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contactListAttachRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a contact list to group contacts
         * @summary Create list
         * @param {ContactListCreateRequest} contactListCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactListCreate: async (contactListCreateRequest: ContactListCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactListCreateRequest' is not null or undefined
            assertParamExists('contactListCreate', 'contactListCreateRequest', contactListCreateRequest)
            const localVarPath = `/api/groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contactListCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Method for deleting contact list. Please note that when you delete a contact list, all contacts that were added to it are not deleted from your Contact Book
         * @summary Delete list
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactListDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contactListDelete', 'id', id)
            const localVarPath = `/api/groups/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Performs the removal of contact from the list. The action can be single (string) or bulk (array)
         * @summary Remove contacts from the list
         * @param {ContactListDetachRequest} contactListDetachRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactListDetach: async (contactListDetachRequest: ContactListDetachRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactListDetachRequest' is not null or undefined
            assertParamExists('contactListDetach', 'contactListDetachRequest', contactListDetachRequest)
            const localVarPath = `/api/groups/detach`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contactListDetachRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Method for searching the list of contacts using operations like, =, >, >=, <, <=. Search is possible by the following fields:   - name - description - date - items - phone - id 
         * @summary Search list
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {ContactListSearchSortEnum} [sort] 
         * @param {SortWay} [way] 
         * @param {ContactGroupSearchField} [searchField] 
         * @param {SearchOperator} [searchOperator] 
         * @param {string} [searchValue] 
         * @param {ContactGroupSearchField} [searchFields0Field] 
         * @param {SearchOperator} [searchFields0Operator] 
         * @param {string} [searchFields0Value] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactListSearch: async (pageOffset?: number, pageLimit?: number, sort?: ContactListSearchSortEnum, way?: SortWay, searchField?: ContactGroupSearchField, searchOperator?: SearchOperator, searchValue?: string, searchFields0Field?: ContactGroupSearchField, searchFields0Operator?: SearchOperator, searchFields0Value?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/groups/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageOffset !== undefined) {
                localVarQueryParameter['page[offset]'] = pageOffset;
            }

            if (pageLimit !== undefined) {
                localVarQueryParameter['page[limit]'] = pageLimit;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (way !== undefined) {
                localVarQueryParameter['way'] = way;
            }

            if (searchField !== undefined) {
                localVarQueryParameter['search[field]'] = searchField;
            }

            if (searchOperator !== undefined) {
                localVarQueryParameter['search[operator]'] = searchOperator;
            }

            if (searchValue !== undefined) {
                localVarQueryParameter['search[value]'] = searchValue;
            }

            if (searchFields0Field !== undefined) {
                localVarQueryParameter['search_fields[0][field]'] = searchFields0Field;
            }

            if (searchFields0Operator !== undefined) {
                localVarQueryParameter['search_fields[0][operator]'] = searchFields0Operator;
            }

            if (searchFields0Value !== undefined) {
                localVarQueryParameter['search_fields[0][value]'] = searchFields0Value;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Performs editing of the selected contacts list
         * @summary Update list
         * @param {number} id 
         * @param {ContactListUpdateRequest} contactListUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactListUpdate: async (id: number, contactListUpdateRequest: ContactListUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contactListUpdate', 'id', id)
            // verify required parameter 'contactListUpdateRequest' is not null or undefined
            assertParamExists('contactListUpdate', 'contactListUpdateRequest', contactListUpdateRequest)
            const localVarPath = `/api/groups/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(contactListUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Provides an index of all the contact lists with data
         * @summary List of contact lists
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactLists: async (pageOffset?: number, pageLimit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageOffset !== undefined) {
                localVarQueryParameter['page[offset]'] = pageOffset;
            }

            if (pageLimit !== undefined) {
                localVarQueryParameter['page[limit]'] = pageLimit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ContactListApi - functional programming interface
 * @export
 */
export const ContactListApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ContactListApiAxiosParamCreator(configuration)
    return {
        /**
         * Get information about the contact list by its identifier
         * @summary Get list by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactList(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactList200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactList(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactListApi.contactList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The method provides the ability to add an existing contact to the list. The action can be single or bulk.
         * @summary Add contacts to the list
         * @param {ContactListAttachRequest} contactListAttachRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactListAttach(contactListAttachRequest: ContactListAttachRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactListAttach(contactListAttachRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactListApi.contactListAttach']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a contact list to group contacts
         * @summary Create list
         * @param {ContactListCreateRequest} contactListCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactListCreate(contactListCreateRequest: ContactListCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactListCreate201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactListCreate(contactListCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactListApi.contactListCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Method for deleting contact list. Please note that when you delete a contact list, all contacts that were added to it are not deleted from your Contact Book
         * @summary Delete list
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactListDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactListDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactListApi.contactListDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Performs the removal of contact from the list. The action can be single (string) or bulk (array)
         * @summary Remove contacts from the list
         * @param {ContactListDetachRequest} contactListDetachRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactListDetach(contactListDetachRequest: ContactListDetachRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactListDetach(contactListDetachRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactListApi.contactListDetach']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Method for searching the list of contacts using operations like, =, >, >=, <, <=. Search is possible by the following fields:   - name - description - date - items - phone - id 
         * @summary Search list
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {ContactListSearchSortEnum} [sort] 
         * @param {SortWay} [way] 
         * @param {ContactGroupSearchField} [searchField] 
         * @param {SearchOperator} [searchOperator] 
         * @param {string} [searchValue] 
         * @param {ContactGroupSearchField} [searchFields0Field] 
         * @param {SearchOperator} [searchFields0Operator] 
         * @param {string} [searchFields0Value] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactListSearch(pageOffset?: number, pageLimit?: number, sort?: ContactListSearchSortEnum, way?: SortWay, searchField?: ContactGroupSearchField, searchOperator?: SearchOperator, searchValue?: string, searchFields0Field?: ContactGroupSearchField, searchFields0Operator?: SearchOperator, searchFields0Value?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactListSearch200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactListSearch(pageOffset, pageLimit, sort, way, searchField, searchOperator, searchValue, searchFields0Field, searchFields0Operator, searchFields0Value, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactListApi.contactListSearch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Performs editing of the selected contacts list
         * @summary Update list
         * @param {number} id 
         * @param {ContactListUpdateRequest} contactListUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactListUpdate(id: number, contactListUpdateRequest: ContactListUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactListUpdate200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactListUpdate(id, contactListUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactListApi.contactListUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Provides an index of all the contact lists with data
         * @summary List of contact lists
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contactLists(pageOffset?: number, pageLimit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContactLists200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contactLists(pageOffset, pageLimit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactListApi.contactLists']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ContactListApi - factory interface
 * @export
 */
export const ContactListApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ContactListApiFp(configuration)
    return {
        /**
         * Get information about the contact list by its identifier
         * @summary Get list by id
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactList(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ContactList200Response> {
            return localVarFp.contactList(id, options).then((request) => request(axios, basePath));
        },
        /**
         * The method provides the ability to add an existing contact to the list. The action can be single or bulk.
         * @summary Add contacts to the list
         * @param {ContactListAttachRequest} contactListAttachRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactListAttach(contactListAttachRequest: ContactListAttachRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.contactListAttach(contactListAttachRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a contact list to group contacts
         * @summary Create list
         * @param {ContactListCreateRequest} contactListCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactListCreate(contactListCreateRequest: ContactListCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactListCreate201Response> {
            return localVarFp.contactListCreate(contactListCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Method for deleting contact list. Please note that when you delete a contact list, all contacts that were added to it are not deleted from your Contact Book
         * @summary Delete list
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactListDelete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.contactListDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Performs the removal of contact from the list. The action can be single (string) or bulk (array)
         * @summary Remove contacts from the list
         * @param {ContactListDetachRequest} contactListDetachRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactListDetach(contactListDetachRequest: ContactListDetachRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.contactListDetach(contactListDetachRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Method for searching the list of contacts using operations like, =, >, >=, <, <=. Search is possible by the following fields:   - name - description - date - items - phone - id 
         * @summary Search list
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {ContactListSearchSortEnum} [sort] 
         * @param {SortWay} [way] 
         * @param {ContactGroupSearchField} [searchField] 
         * @param {SearchOperator} [searchOperator] 
         * @param {string} [searchValue] 
         * @param {ContactGroupSearchField} [searchFields0Field] 
         * @param {SearchOperator} [searchFields0Operator] 
         * @param {string} [searchFields0Value] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactListSearch(pageOffset?: number, pageLimit?: number, sort?: ContactListSearchSortEnum, way?: SortWay, searchField?: ContactGroupSearchField, searchOperator?: SearchOperator, searchValue?: string, searchFields0Field?: ContactGroupSearchField, searchFields0Operator?: SearchOperator, searchFields0Value?: string, options?: RawAxiosRequestConfig): AxiosPromise<ContactListSearch200Response> {
            return localVarFp.contactListSearch(pageOffset, pageLimit, sort, way, searchField, searchOperator, searchValue, searchFields0Field, searchFields0Operator, searchFields0Value, options).then((request) => request(axios, basePath));
        },
        /**
         * Performs editing of the selected contacts list
         * @summary Update list
         * @param {number} id 
         * @param {ContactListUpdateRequest} contactListUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactListUpdate(id: number, contactListUpdateRequest: ContactListUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactListUpdate200Response> {
            return localVarFp.contactListUpdate(id, contactListUpdateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Provides an index of all the contact lists with data
         * @summary List of contact lists
         * @param {number} [pageOffset] 
         * @param {number} [pageLimit] The number of items in the response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contactLists(pageOffset?: number, pageLimit?: number, options?: RawAxiosRequestConfig): AxiosPromise<ContactLists200Response> {
            return localVarFp.contactLists(pageOffset, pageLimit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ContactListApi - interface
 * @export
 * @interface ContactListApi
 */
export interface ContactListApiInterface {
    /**
     * Get information about the contact list by its identifier
     * @summary Get list by id
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApiInterface
     */
    contactList(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ContactList200Response>;

    /**
     * The method provides the ability to add an existing contact to the list. The action can be single or bulk.
     * @summary Add contacts to the list
     * @param {ContactListAttachRequest} contactListAttachRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApiInterface
     */
    contactListAttach(contactListAttachRequest: ContactListAttachRequest, options?: RawAxiosRequestConfig): AxiosPromise<object>;

    /**
     * Create a contact list to group contacts
     * @summary Create list
     * @param {ContactListCreateRequest} contactListCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApiInterface
     */
    contactListCreate(contactListCreateRequest: ContactListCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactListCreate201Response>;

    /**
     * Method for deleting contact list. Please note that when you delete a contact list, all contacts that were added to it are not deleted from your Contact Book
     * @summary Delete list
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApiInterface
     */
    contactListDelete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Performs the removal of contact from the list. The action can be single (string) or bulk (array)
     * @summary Remove contacts from the list
     * @param {ContactListDetachRequest} contactListDetachRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApiInterface
     */
    contactListDetach(contactListDetachRequest: ContactListDetachRequest, options?: RawAxiosRequestConfig): AxiosPromise<object>;

    /**
     * Method for searching the list of contacts using operations like, =, >, >=, <, <=. Search is possible by the following fields:   - name - description - date - items - phone - id 
     * @summary Search list
     * @param {number} [pageOffset] 
     * @param {number} [pageLimit] The number of items in the response
     * @param {ContactListSearchSortEnum} [sort] 
     * @param {SortWay} [way] 
     * @param {ContactGroupSearchField} [searchField] 
     * @param {SearchOperator} [searchOperator] 
     * @param {string} [searchValue] 
     * @param {ContactGroupSearchField} [searchFields0Field] 
     * @param {SearchOperator} [searchFields0Operator] 
     * @param {string} [searchFields0Value] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApiInterface
     */
    contactListSearch(pageOffset?: number, pageLimit?: number, sort?: ContactListSearchSortEnum, way?: SortWay, searchField?: ContactGroupSearchField, searchOperator?: SearchOperator, searchValue?: string, searchFields0Field?: ContactGroupSearchField, searchFields0Operator?: SearchOperator, searchFields0Value?: string, options?: RawAxiosRequestConfig): AxiosPromise<ContactListSearch200Response>;

    /**
     * Performs editing of the selected contacts list
     * @summary Update list
     * @param {number} id 
     * @param {ContactListUpdateRequest} contactListUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApiInterface
     */
    contactListUpdate(id: number, contactListUpdateRequest: ContactListUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContactListUpdate200Response>;

    /**
     * Provides an index of all the contact lists with data
     * @summary List of contact lists
     * @param {number} [pageOffset] 
     * @param {number} [pageLimit] The number of items in the response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApiInterface
     */
    contactLists(pageOffset?: number, pageLimit?: number, options?: RawAxiosRequestConfig): AxiosPromise<ContactLists200Response>;

}

/**
 * ContactListApi - object-oriented interface
 * @export
 * @class ContactListApi
 * @extends {BaseAPI}
 */
export class ContactListApi extends BaseAPI implements ContactListApiInterface {
    /**
     * Get information about the contact list by its identifier
     * @summary Get list by id
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApi
     */
    public contactList(id: number, options?: RawAxiosRequestConfig) {
        return ContactListApiFp(this.configuration).contactList(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The method provides the ability to add an existing contact to the list. The action can be single or bulk.
     * @summary Add contacts to the list
     * @param {ContactListAttachRequest} contactListAttachRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApi
     */
    public contactListAttach(contactListAttachRequest: ContactListAttachRequest, options?: RawAxiosRequestConfig) {
        return ContactListApiFp(this.configuration).contactListAttach(contactListAttachRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a contact list to group contacts
     * @summary Create list
     * @param {ContactListCreateRequest} contactListCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApi
     */
    public contactListCreate(contactListCreateRequest: ContactListCreateRequest, options?: RawAxiosRequestConfig) {
        return ContactListApiFp(this.configuration).contactListCreate(contactListCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Method for deleting contact list. Please note that when you delete a contact list, all contacts that were added to it are not deleted from your Contact Book
     * @summary Delete list
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApi
     */
    public contactListDelete(id: number, options?: RawAxiosRequestConfig) {
        return ContactListApiFp(this.configuration).contactListDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Performs the removal of contact from the list. The action can be single (string) or bulk (array)
     * @summary Remove contacts from the list
     * @param {ContactListDetachRequest} contactListDetachRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApi
     */
    public contactListDetach(contactListDetachRequest: ContactListDetachRequest, options?: RawAxiosRequestConfig) {
        return ContactListApiFp(this.configuration).contactListDetach(contactListDetachRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Method for searching the list of contacts using operations like, =, >, >=, <, <=. Search is possible by the following fields:   - name - description - date - items - phone - id 
     * @summary Search list
     * @param {number} [pageOffset] 
     * @param {number} [pageLimit] The number of items in the response
     * @param {ContactListSearchSortEnum} [sort] 
     * @param {SortWay} [way] 
     * @param {ContactGroupSearchField} [searchField] 
     * @param {SearchOperator} [searchOperator] 
     * @param {string} [searchValue] 
     * @param {ContactGroupSearchField} [searchFields0Field] 
     * @param {SearchOperator} [searchFields0Operator] 
     * @param {string} [searchFields0Value] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApi
     */
    public contactListSearch(pageOffset?: number, pageLimit?: number, sort?: ContactListSearchSortEnum, way?: SortWay, searchField?: ContactGroupSearchField, searchOperator?: SearchOperator, searchValue?: string, searchFields0Field?: ContactGroupSearchField, searchFields0Operator?: SearchOperator, searchFields0Value?: string, options?: RawAxiosRequestConfig) {
        return ContactListApiFp(this.configuration).contactListSearch(pageOffset, pageLimit, sort, way, searchField, searchOperator, searchValue, searchFields0Field, searchFields0Operator, searchFields0Value, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Performs editing of the selected contacts list
     * @summary Update list
     * @param {number} id 
     * @param {ContactListUpdateRequest} contactListUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApi
     */
    public contactListUpdate(id: number, contactListUpdateRequest: ContactListUpdateRequest, options?: RawAxiosRequestConfig) {
        return ContactListApiFp(this.configuration).contactListUpdate(id, contactListUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Provides an index of all the contact lists with data
     * @summary List of contact lists
     * @param {number} [pageOffset] 
     * @param {number} [pageLimit] The number of items in the response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContactListApi
     */
    public contactLists(pageOffset?: number, pageLimit?: number, options?: RawAxiosRequestConfig) {
        return ContactListApiFp(this.configuration).contactLists(pageOffset, pageLimit, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const ContactListSearchSortEnum = {
    Id: 'id',
    Items: 'items',
    Name: 'name',
    Description: 'description',
    CreatedAt: 'created_at'
} as const;
export type ContactListSearchSortEnum = typeof ContactListSearchSortEnum[keyof typeof ContactListSearchSortEnum];
