/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GetInternalCorePrices200Response } from '../models';
// @ts-ignore
import type { GetInternalCorePricesByCountryCode200Response } from '../models';
/**
 * InternalCorePriceApi - axios parameter creator
 * @export
 */
export const InternalCorePriceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get price list for each country
         * @param {GetInternalCorePricesProductEnum} product Product value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInternalCorePrices: async (product: GetInternalCorePricesProductEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'product' is not null or undefined
            assertParamExists('getInternalCorePrices', 'product', product)
            const localVarPath = `/api/internal/core/prices`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication InternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (product !== undefined) {
                localVarQueryParameter['product'] = product;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get prices for country
         * @param {string} countryCode Country ISO Code
         * @param {GetInternalCorePricesByCountryCodeProductEnum} product Product value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInternalCorePricesByCountryCode: async (countryCode: string, product: GetInternalCorePricesByCountryCodeProductEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'countryCode' is not null or undefined
            assertParamExists('getInternalCorePricesByCountryCode', 'countryCode', countryCode)
            // verify required parameter 'product' is not null or undefined
            assertParamExists('getInternalCorePricesByCountryCode', 'product', product)
            const localVarPath = `/api/internal/core/prices/{countryCode}`
                .replace(`{${"countryCode"}}`, encodeURIComponent(String(countryCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication InternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (product !== undefined) {
                localVarQueryParameter['product'] = product;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InternalCorePriceApi - functional programming interface
 * @export
 */
export const InternalCorePriceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InternalCorePriceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get price list for each country
         * @param {GetInternalCorePricesProductEnum} product Product value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInternalCorePrices(product: GetInternalCorePricesProductEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetInternalCorePrices200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInternalCorePrices(product, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InternalCorePriceApi.getInternalCorePrices']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get prices for country
         * @param {string} countryCode Country ISO Code
         * @param {GetInternalCorePricesByCountryCodeProductEnum} product Product value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInternalCorePricesByCountryCode(countryCode: string, product: GetInternalCorePricesByCountryCodeProductEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetInternalCorePricesByCountryCode200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInternalCorePricesByCountryCode(countryCode, product, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InternalCorePriceApi.getInternalCorePricesByCountryCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InternalCorePriceApi - factory interface
 * @export
 */
export const InternalCorePriceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InternalCorePriceApiFp(configuration)
    return {
        /**
         * 
         * @summary Get price list for each country
         * @param {GetInternalCorePricesProductEnum} product Product value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInternalCorePrices(product: GetInternalCorePricesProductEnum, options?: RawAxiosRequestConfig): AxiosPromise<GetInternalCorePrices200Response> {
            return localVarFp.getInternalCorePrices(product, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get prices for country
         * @param {string} countryCode Country ISO Code
         * @param {GetInternalCorePricesByCountryCodeProductEnum} product Product value
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInternalCorePricesByCountryCode(countryCode: string, product: GetInternalCorePricesByCountryCodeProductEnum, options?: RawAxiosRequestConfig): AxiosPromise<GetInternalCorePricesByCountryCode200Response> {
            return localVarFp.getInternalCorePricesByCountryCode(countryCode, product, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InternalCorePriceApi - interface
 * @export
 * @interface InternalCorePriceApi
 */
export interface InternalCorePriceApiInterface {
    /**
     * 
     * @summary Get price list for each country
     * @param {GetInternalCorePricesProductEnum} product Product value
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InternalCorePriceApiInterface
     */
    getInternalCorePrices(product: GetInternalCorePricesProductEnum, options?: RawAxiosRequestConfig): AxiosPromise<GetInternalCorePrices200Response>;

    /**
     * 
     * @summary Get prices for country
     * @param {string} countryCode Country ISO Code
     * @param {GetInternalCorePricesByCountryCodeProductEnum} product Product value
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InternalCorePriceApiInterface
     */
    getInternalCorePricesByCountryCode(countryCode: string, product: GetInternalCorePricesByCountryCodeProductEnum, options?: RawAxiosRequestConfig): AxiosPromise<GetInternalCorePricesByCountryCode200Response>;

}

/**
 * InternalCorePriceApi - object-oriented interface
 * @export
 * @class InternalCorePriceApi
 * @extends {BaseAPI}
 */
export class InternalCorePriceApi extends BaseAPI implements InternalCorePriceApiInterface {
    /**
     * 
     * @summary Get price list for each country
     * @param {GetInternalCorePricesProductEnum} product Product value
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InternalCorePriceApi
     */
    public getInternalCorePrices(product: GetInternalCorePricesProductEnum, options?: RawAxiosRequestConfig) {
        return InternalCorePriceApiFp(this.configuration).getInternalCorePrices(product, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get prices for country
     * @param {string} countryCode Country ISO Code
     * @param {GetInternalCorePricesByCountryCodeProductEnum} product Product value
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InternalCorePriceApi
     */
    public getInternalCorePricesByCountryCode(countryCode: string, product: GetInternalCorePricesByCountryCodeProductEnum, options?: RawAxiosRequestConfig) {
        return InternalCorePriceApiFp(this.configuration).getInternalCorePricesByCountryCode(countryCode, product, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetInternalCorePricesProductEnum = {
    Sms: 'sms',
    Viber: 'viber',
    Otp: 'otp',
    Hlr: 'hlr'
} as const;
export type GetInternalCorePricesProductEnum = typeof GetInternalCorePricesProductEnum[keyof typeof GetInternalCorePricesProductEnum];
/**
 * @export
 */
export const GetInternalCorePricesByCountryCodeProductEnum = {
    Sms: 'sms',
    Viber: 'viber',
    Otp: 'otp',
    Hlr: 'hlr'
} as const;
export type GetInternalCorePricesByCountryCodeProductEnum = typeof GetInternalCorePricesByCountryCodeProductEnum[keyof typeof GetInternalCorePricesByCountryCodeProductEnum];
