/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GetInternalCountries200Response } from '../models';
/**
 * InternalCountryApi - axios parameter creator
 * @export
 */
export const InternalCountryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get countries list
         * @param {GetInternalCountriesServiceEnum} [service] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInternalCountries: async (service?: GetInternalCountriesServiceEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/internal/countries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication InternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (service !== undefined) {
                localVarQueryParameter['service'] = service;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InternalCountryApi - functional programming interface
 * @export
 */
export const InternalCountryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InternalCountryApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get countries list
         * @param {GetInternalCountriesServiceEnum} [service] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInternalCountries(service?: GetInternalCountriesServiceEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetInternalCountries200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInternalCountries(service, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InternalCountryApi.getInternalCountries']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InternalCountryApi - factory interface
 * @export
 */
export const InternalCountryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InternalCountryApiFp(configuration)
    return {
        /**
         * 
         * @summary Get countries list
         * @param {GetInternalCountriesServiceEnum} [service] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInternalCountries(service?: GetInternalCountriesServiceEnum, options?: RawAxiosRequestConfig): AxiosPromise<GetInternalCountries200Response> {
            return localVarFp.getInternalCountries(service, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InternalCountryApi - interface
 * @export
 * @interface InternalCountryApi
 */
export interface InternalCountryApiInterface {
    /**
     * 
     * @summary Get countries list
     * @param {GetInternalCountriesServiceEnum} [service] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InternalCountryApiInterface
     */
    getInternalCountries(service?: GetInternalCountriesServiceEnum, options?: RawAxiosRequestConfig): AxiosPromise<GetInternalCountries200Response>;

}

/**
 * InternalCountryApi - object-oriented interface
 * @export
 * @class InternalCountryApi
 * @extends {BaseAPI}
 */
export class InternalCountryApi extends BaseAPI implements InternalCountryApiInterface {
    /**
     * 
     * @summary Get countries list
     * @param {GetInternalCountriesServiceEnum} [service] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InternalCountryApi
     */
    public getInternalCountries(service?: GetInternalCountriesServiceEnum, options?: RawAxiosRequestConfig) {
        return InternalCountryApiFp(this.configuration).getInternalCountries(service, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetInternalCountriesServiceEnum = {
    Sms: 'sms',
    Viber: 'viber',
    Twoway: 'twoway'
} as const;
export type GetInternalCountriesServiceEnum = typeof GetInternalCountriesServiceEnum[keyof typeof GetInternalCountriesServiceEnum];
