/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GetInternal2faAuthenticationsFullPrice200Response } from '../models';
/**
 * InternalTwoFAApi - axios parameter creator
 * @export
 */
export const InternalTwoFAApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Show TwoFA authentication full price
         * @param {GetInternal2faAuthenticationsFullPriceChannelTypeEnum} channelType 
         * @param {string} currency 
         * @param {GetInternal2faAuthenticationsFullPriceTariffCodeEnum} [tariffCode] 
         * @param {string} [countryCode] 
         * @param {number} [operatorId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInternal2faAuthenticationsFullPrice: async (channelType: GetInternal2faAuthenticationsFullPriceChannelTypeEnum, currency: string, tariffCode?: GetInternal2faAuthenticationsFullPriceTariffCodeEnum, countryCode?: string, operatorId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'channelType' is not null or undefined
            assertParamExists('getInternal2faAuthenticationsFullPrice', 'channelType', channelType)
            // verify required parameter 'currency' is not null or undefined
            assertParamExists('getInternal2faAuthenticationsFullPrice', 'currency', currency)
            const localVarPath = `/api/internal/2fa/authentications/full-price`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (channelType !== undefined) {
                localVarQueryParameter['channel_type'] = channelType;
            }

            if (tariffCode !== undefined) {
                localVarQueryParameter['tariff_code'] = tariffCode;
            }

            if (countryCode !== undefined) {
                localVarQueryParameter['country_code'] = countryCode;
            }

            if (operatorId !== undefined) {
                localVarQueryParameter['operator_id'] = operatorId;
            }

            if (currency !== undefined) {
                localVarQueryParameter['currency'] = currency;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InternalTwoFAApi - functional programming interface
 * @export
 */
export const InternalTwoFAApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InternalTwoFAApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Show TwoFA authentication full price
         * @param {GetInternal2faAuthenticationsFullPriceChannelTypeEnum} channelType 
         * @param {string} currency 
         * @param {GetInternal2faAuthenticationsFullPriceTariffCodeEnum} [tariffCode] 
         * @param {string} [countryCode] 
         * @param {number} [operatorId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInternal2faAuthenticationsFullPrice(channelType: GetInternal2faAuthenticationsFullPriceChannelTypeEnum, currency: string, tariffCode?: GetInternal2faAuthenticationsFullPriceTariffCodeEnum, countryCode?: string, operatorId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetInternal2faAuthenticationsFullPrice200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInternal2faAuthenticationsFullPrice(channelType, currency, tariffCode, countryCode, operatorId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InternalTwoFAApi.getInternal2faAuthenticationsFullPrice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InternalTwoFAApi - factory interface
 * @export
 */
export const InternalTwoFAApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InternalTwoFAApiFp(configuration)
    return {
        /**
         * 
         * @summary Show TwoFA authentication full price
         * @param {GetInternal2faAuthenticationsFullPriceChannelTypeEnum} channelType 
         * @param {string} currency 
         * @param {GetInternal2faAuthenticationsFullPriceTariffCodeEnum} [tariffCode] 
         * @param {string} [countryCode] 
         * @param {number} [operatorId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInternal2faAuthenticationsFullPrice(channelType: GetInternal2faAuthenticationsFullPriceChannelTypeEnum, currency: string, tariffCode?: GetInternal2faAuthenticationsFullPriceTariffCodeEnum, countryCode?: string, operatorId?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetInternal2faAuthenticationsFullPrice200Response> {
            return localVarFp.getInternal2faAuthenticationsFullPrice(channelType, currency, tariffCode, countryCode, operatorId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InternalTwoFAApi - interface
 * @export
 * @interface InternalTwoFAApi
 */
export interface InternalTwoFAApiInterface {
    /**
     * 
     * @summary Show TwoFA authentication full price
     * @param {GetInternal2faAuthenticationsFullPriceChannelTypeEnum} channelType 
     * @param {string} currency 
     * @param {GetInternal2faAuthenticationsFullPriceTariffCodeEnum} [tariffCode] 
     * @param {string} [countryCode] 
     * @param {number} [operatorId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InternalTwoFAApiInterface
     */
    getInternal2faAuthenticationsFullPrice(channelType: GetInternal2faAuthenticationsFullPriceChannelTypeEnum, currency: string, tariffCode?: GetInternal2faAuthenticationsFullPriceTariffCodeEnum, countryCode?: string, operatorId?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetInternal2faAuthenticationsFullPrice200Response>;

}

/**
 * InternalTwoFAApi - object-oriented interface
 * @export
 * @class InternalTwoFAApi
 * @extends {BaseAPI}
 */
export class InternalTwoFAApi extends BaseAPI implements InternalTwoFAApiInterface {
    /**
     * 
     * @summary Show TwoFA authentication full price
     * @param {GetInternal2faAuthenticationsFullPriceChannelTypeEnum} channelType 
     * @param {string} currency 
     * @param {GetInternal2faAuthenticationsFullPriceTariffCodeEnum} [tariffCode] 
     * @param {string} [countryCode] 
     * @param {number} [operatorId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InternalTwoFAApi
     */
    public getInternal2faAuthenticationsFullPrice(channelType: GetInternal2faAuthenticationsFullPriceChannelTypeEnum, currency: string, tariffCode?: GetInternal2faAuthenticationsFullPriceTariffCodeEnum, countryCode?: string, operatorId?: number, options?: RawAxiosRequestConfig) {
        return InternalTwoFAApiFp(this.configuration).getInternal2faAuthenticationsFullPrice(channelType, currency, tariffCode, countryCode, operatorId, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetInternal2faAuthenticationsFullPriceChannelTypeEnum = {
    Sms: 'sms'
} as const;
export type GetInternal2faAuthenticationsFullPriceChannelTypeEnum = typeof GetInternal2faAuthenticationsFullPriceChannelTypeEnum[keyof typeof GetInternal2faAuthenticationsFullPriceChannelTypeEnum];
/**
 * @export
 */
export const GetInternal2faAuthenticationsFullPriceTariffCodeEnum = {
    NUMBER_28: 28
} as const;
export type GetInternal2faAuthenticationsFullPriceTariffCodeEnum = typeof GetInternal2faAuthenticationsFullPriceTariffCodeEnum[keyof typeof GetInternal2faAuthenticationsFullPriceTariffCodeEnum];
