/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SenderRequestLegal201Response } from '../models';
// @ts-ignore
import type { SenderRequestLegalRequest } from '../models';
// @ts-ignore
import type { SenderRequestNatural201Response } from '../models';
// @ts-ignore
import type { SenderRequestNaturalRequest } from '../models';
// @ts-ignore
import type { SenderRequestStatus } from '../models';
// @ts-ignore
import type { SenderRequests200Response } from '../models';
// @ts-ignore
import type { Senders200Response } from '../models';
// @ts-ignore
import type { SortWay } from '../models';
// @ts-ignore
import type { TooManyRequestsResponse } from '../models';
/**
 * SendersApi - axios parameter creator
 * @export
 */
export const SendersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Method for submitting an application for registration of the SMS Sender’s name (Alpha-name) with a mobile operator by a subject legal entity.  **Please note:** that Sender registration is not available in Demo and Test account modes.
         * @summary Sender registration by a legal entity
         * @param {SenderRequestLegalRequest} senderRequestLegalRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        senderRequestLegal: async (senderRequestLegalRequest: SenderRequestLegalRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'senderRequestLegalRequest' is not null or undefined
            assertParamExists('senderRequestLegal', 'senderRequestLegalRequest', senderRequestLegalRequest)
            const localVarPath = `/api/senders/requests/legal`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(senderRequestLegalRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Method for submitting an application for registration of the SMS Sender’s name (Alpha-name) with a mobile operator by a subject individual.  **Please note:** that Sender registration is not available in Demo and Test account modes.
         * @summary Sender registration by an individual
         * @param {SenderRequestNaturalRequest} senderRequestNaturalRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        senderRequestNatural: async (senderRequestNaturalRequest: SenderRequestNaturalRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'senderRequestNaturalRequest' is not null or undefined
            assertParamExists('senderRequestNatural', 'senderRequestNaturalRequest', senderRequestNaturalRequest)
            const localVarPath = `/api/senders/requests/natural`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(senderRequestNaturalRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get SMS Senders request status
         * @summary List of Sender Requests
         * @param {number} [pageLimit] 
         * @param {number} [pageOffset] 
         * @param {SenderRequestsSortEnum} [sort] 
         * @param {SortWay} [way] 
         * @param {SenderRequestStatus} [filterStatus] 
         * @param {number} [filterId] 
         * @param {string} [filterCountryCode] 
         * @param {string} [filterSender] 
         * @param {string} [filterCreatedAt] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        senderRequests: async (pageLimit?: number, pageOffset?: number, sort?: SenderRequestsSortEnum, way?: SortWay, filterStatus?: SenderRequestStatus, filterId?: number, filterCountryCode?: string, filterSender?: string, filterCreatedAt?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/senders/requests/sms`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageLimit !== undefined) {
                localVarQueryParameter['page[limit]'] = pageLimit;
            }

            if (pageOffset !== undefined) {
                localVarQueryParameter['page[offset]'] = pageOffset;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (way !== undefined) {
                localVarQueryParameter['way'] = way;
            }

            if (filterStatus !== undefined) {
                localVarQueryParameter['filter[status]'] = filterStatus;
            }

            if (filterId !== undefined) {
                localVarQueryParameter['filter[id]'] = filterId;
            }

            if (filterCountryCode !== undefined) {
                localVarQueryParameter['filter[country_code]'] = filterCountryCode;
            }

            if (filterSender !== undefined) {
                localVarQueryParameter['filter[sender]'] = filterSender;
            }

            if (filterCreatedAt !== undefined) {
                localVarQueryParameter['filter[created_at]'] = (filterCreatedAt as any instanceof Date) ?
                    (filterCreatedAt as any).toISOString() :
                    filterCreatedAt;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the list of the registered senders
         * @summary List of Senders
         * @param {SendersTypeEnum} type Sender type to list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        senders: async (type: SendersTypeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            assertParamExists('senders', 'type', type)
            const localVarPath = `/api/senders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SendersApi - functional programming interface
 * @export
 */
export const SendersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SendersApiAxiosParamCreator(configuration)
    return {
        /**
         * Method for submitting an application for registration of the SMS Sender’s name (Alpha-name) with a mobile operator by a subject legal entity.  **Please note:** that Sender registration is not available in Demo and Test account modes.
         * @summary Sender registration by a legal entity
         * @param {SenderRequestLegalRequest} senderRequestLegalRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async senderRequestLegal(senderRequestLegalRequest: SenderRequestLegalRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SenderRequestLegal201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.senderRequestLegal(senderRequestLegalRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SendersApi.senderRequestLegal']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Method for submitting an application for registration of the SMS Sender’s name (Alpha-name) with a mobile operator by a subject individual.  **Please note:** that Sender registration is not available in Demo and Test account modes.
         * @summary Sender registration by an individual
         * @param {SenderRequestNaturalRequest} senderRequestNaturalRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async senderRequestNatural(senderRequestNaturalRequest: SenderRequestNaturalRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SenderRequestNatural201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.senderRequestNatural(senderRequestNaturalRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SendersApi.senderRequestNatural']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get SMS Senders request status
         * @summary List of Sender Requests
         * @param {number} [pageLimit] 
         * @param {number} [pageOffset] 
         * @param {SenderRequestsSortEnum} [sort] 
         * @param {SortWay} [way] 
         * @param {SenderRequestStatus} [filterStatus] 
         * @param {number} [filterId] 
         * @param {string} [filterCountryCode] 
         * @param {string} [filterSender] 
         * @param {string} [filterCreatedAt] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async senderRequests(pageLimit?: number, pageOffset?: number, sort?: SenderRequestsSortEnum, way?: SortWay, filterStatus?: SenderRequestStatus, filterId?: number, filterCountryCode?: string, filterSender?: string, filterCreatedAt?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SenderRequests200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.senderRequests(pageLimit, pageOffset, sort, way, filterStatus, filterId, filterCountryCode, filterSender, filterCreatedAt, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SendersApi.senderRequests']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get the list of the registered senders
         * @summary List of Senders
         * @param {SendersTypeEnum} type Sender type to list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async senders(type: SendersTypeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Senders200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.senders(type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SendersApi.senders']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SendersApi - factory interface
 * @export
 */
export const SendersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SendersApiFp(configuration)
    return {
        /**
         * Method for submitting an application for registration of the SMS Sender’s name (Alpha-name) with a mobile operator by a subject legal entity.  **Please note:** that Sender registration is not available in Demo and Test account modes.
         * @summary Sender registration by a legal entity
         * @param {SenderRequestLegalRequest} senderRequestLegalRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        senderRequestLegal(senderRequestLegalRequest: SenderRequestLegalRequest, options?: RawAxiosRequestConfig): AxiosPromise<SenderRequestLegal201Response> {
            return localVarFp.senderRequestLegal(senderRequestLegalRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Method for submitting an application for registration of the SMS Sender’s name (Alpha-name) with a mobile operator by a subject individual.  **Please note:** that Sender registration is not available in Demo and Test account modes.
         * @summary Sender registration by an individual
         * @param {SenderRequestNaturalRequest} senderRequestNaturalRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        senderRequestNatural(senderRequestNaturalRequest: SenderRequestNaturalRequest, options?: RawAxiosRequestConfig): AxiosPromise<SenderRequestNatural201Response> {
            return localVarFp.senderRequestNatural(senderRequestNaturalRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get SMS Senders request status
         * @summary List of Sender Requests
         * @param {number} [pageLimit] 
         * @param {number} [pageOffset] 
         * @param {SenderRequestsSortEnum} [sort] 
         * @param {SortWay} [way] 
         * @param {SenderRequestStatus} [filterStatus] 
         * @param {number} [filterId] 
         * @param {string} [filterCountryCode] 
         * @param {string} [filterSender] 
         * @param {string} [filterCreatedAt] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        senderRequests(pageLimit?: number, pageOffset?: number, sort?: SenderRequestsSortEnum, way?: SortWay, filterStatus?: SenderRequestStatus, filterId?: number, filterCountryCode?: string, filterSender?: string, filterCreatedAt?: string, options?: RawAxiosRequestConfig): AxiosPromise<SenderRequests200Response> {
            return localVarFp.senderRequests(pageLimit, pageOffset, sort, way, filterStatus, filterId, filterCountryCode, filterSender, filterCreatedAt, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the list of the registered senders
         * @summary List of Senders
         * @param {SendersTypeEnum} type Sender type to list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        senders(type: SendersTypeEnum, options?: RawAxiosRequestConfig): AxiosPromise<Senders200Response> {
            return localVarFp.senders(type, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SendersApi - interface
 * @export
 * @interface SendersApi
 */
export interface SendersApiInterface {
    /**
     * Method for submitting an application for registration of the SMS Sender’s name (Alpha-name) with a mobile operator by a subject legal entity.  **Please note:** that Sender registration is not available in Demo and Test account modes.
     * @summary Sender registration by a legal entity
     * @param {SenderRequestLegalRequest} senderRequestLegalRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SendersApiInterface
     */
    senderRequestLegal(senderRequestLegalRequest: SenderRequestLegalRequest, options?: RawAxiosRequestConfig): AxiosPromise<SenderRequestLegal201Response>;

    /**
     * Method for submitting an application for registration of the SMS Sender’s name (Alpha-name) with a mobile operator by a subject individual.  **Please note:** that Sender registration is not available in Demo and Test account modes.
     * @summary Sender registration by an individual
     * @param {SenderRequestNaturalRequest} senderRequestNaturalRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SendersApiInterface
     */
    senderRequestNatural(senderRequestNaturalRequest: SenderRequestNaturalRequest, options?: RawAxiosRequestConfig): AxiosPromise<SenderRequestNatural201Response>;

    /**
     * Get SMS Senders request status
     * @summary List of Sender Requests
     * @param {number} [pageLimit] 
     * @param {number} [pageOffset] 
     * @param {SenderRequestsSortEnum} [sort] 
     * @param {SortWay} [way] 
     * @param {SenderRequestStatus} [filterStatus] 
     * @param {number} [filterId] 
     * @param {string} [filterCountryCode] 
     * @param {string} [filterSender] 
     * @param {string} [filterCreatedAt] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SendersApiInterface
     */
    senderRequests(pageLimit?: number, pageOffset?: number, sort?: SenderRequestsSortEnum, way?: SortWay, filterStatus?: SenderRequestStatus, filterId?: number, filterCountryCode?: string, filterSender?: string, filterCreatedAt?: string, options?: RawAxiosRequestConfig): AxiosPromise<SenderRequests200Response>;

    /**
     * Get the list of the registered senders
     * @summary List of Senders
     * @param {SendersTypeEnum} type Sender type to list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SendersApiInterface
     */
    senders(type: SendersTypeEnum, options?: RawAxiosRequestConfig): AxiosPromise<Senders200Response>;

}

/**
 * SendersApi - object-oriented interface
 * @export
 * @class SendersApi
 * @extends {BaseAPI}
 */
export class SendersApi extends BaseAPI implements SendersApiInterface {
    /**
     * Method for submitting an application for registration of the SMS Sender’s name (Alpha-name) with a mobile operator by a subject legal entity.  **Please note:** that Sender registration is not available in Demo and Test account modes.
     * @summary Sender registration by a legal entity
     * @param {SenderRequestLegalRequest} senderRequestLegalRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SendersApi
     */
    public senderRequestLegal(senderRequestLegalRequest: SenderRequestLegalRequest, options?: RawAxiosRequestConfig) {
        return SendersApiFp(this.configuration).senderRequestLegal(senderRequestLegalRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Method for submitting an application for registration of the SMS Sender’s name (Alpha-name) with a mobile operator by a subject individual.  **Please note:** that Sender registration is not available in Demo and Test account modes.
     * @summary Sender registration by an individual
     * @param {SenderRequestNaturalRequest} senderRequestNaturalRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SendersApi
     */
    public senderRequestNatural(senderRequestNaturalRequest: SenderRequestNaturalRequest, options?: RawAxiosRequestConfig) {
        return SendersApiFp(this.configuration).senderRequestNatural(senderRequestNaturalRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get SMS Senders request status
     * @summary List of Sender Requests
     * @param {number} [pageLimit] 
     * @param {number} [pageOffset] 
     * @param {SenderRequestsSortEnum} [sort] 
     * @param {SortWay} [way] 
     * @param {SenderRequestStatus} [filterStatus] 
     * @param {number} [filterId] 
     * @param {string} [filterCountryCode] 
     * @param {string} [filterSender] 
     * @param {string} [filterCreatedAt] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SendersApi
     */
    public senderRequests(pageLimit?: number, pageOffset?: number, sort?: SenderRequestsSortEnum, way?: SortWay, filterStatus?: SenderRequestStatus, filterId?: number, filterCountryCode?: string, filterSender?: string, filterCreatedAt?: string, options?: RawAxiosRequestConfig) {
        return SendersApiFp(this.configuration).senderRequests(pageLimit, pageOffset, sort, way, filterStatus, filterId, filterCountryCode, filterSender, filterCreatedAt, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the list of the registered senders
     * @summary List of Senders
     * @param {SendersTypeEnum} type Sender type to list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SendersApi
     */
    public senders(type: SendersTypeEnum, options?: RawAxiosRequestConfig) {
        return SendersApiFp(this.configuration).senders(type, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const SenderRequestsSortEnum = {
    Id: 'id',
    Sender: 'sender',
    Status: 'status',
    CountryCode: 'country_code',
    CreatedAt: 'created_at'
} as const;
export type SenderRequestsSortEnum = typeof SenderRequestsSortEnum[keyof typeof SenderRequestsSortEnum];
/**
 * @export
 */
export const SendersTypeEnum = {
    Sms: 'sms',
    Viber: 'viber'
} as const;
export type SendersTypeEnum = typeof SendersTypeEnum[keyof typeof SendersTypeEnum];
