/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DomainStoreRequest } from '../models';
// @ts-ignore
import type { DomainUpdateRequest } from '../models';
// @ts-ignore
import type { ShortDomainNotFound } from '../models';
// @ts-ignore
import type { ShortUrlsDomain200Response } from '../models';
// @ts-ignore
import type { ShortUrlsDomainCreate201Response } from '../models';
// @ts-ignore
import type { ShortUrlsDomainCreate422Response } from '../models';
// @ts-ignore
import type { ShortUrlsDomainUpdate200Response } from '../models';
// @ts-ignore
import type { ShortUrlsDomains200Response } from '../models';
// @ts-ignore
import type { TooManyRequestsResponse } from '../models';
/**
 * ShortDomainsApi - axios parameter creator
 * @export
 */
export const ShortDomainsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get domain by uuid
         * @param {string} uuid Uuid of entity
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        shortUrlsDomain: async (uuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uuid' is not null or undefined
            assertParamExists('shortUrlsDomain', 'uuid', uuid)
            const localVarPath = `/api/short-url/domains/{uuid}`
                .replace(`{${"uuid"}}`, encodeURIComponent(String(uuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Add domain
         * @param {DomainStoreRequest} [domainStoreRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        shortUrlsDomainCreate: async (domainStoreRequest?: DomainStoreRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/short-url/domains`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(domainStoreRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Remove domain
         * @param {string} uuid Uuid of entity
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        shortUrlsDomainRemove: async (uuid: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uuid' is not null or undefined
            assertParamExists('shortUrlsDomainRemove', 'uuid', uuid)
            const localVarPath = `/api/short-url/domains/{uuid}`
                .replace(`{${"uuid"}}`, encodeURIComponent(String(uuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update domain
         * @param {string} uuid Uuid of entity
         * @param {DomainUpdateRequest} domainUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        shortUrlsDomainUpdate: async (uuid: string, domainUpdateRequest: DomainUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uuid' is not null or undefined
            assertParamExists('shortUrlsDomainUpdate', 'uuid', uuid)
            // verify required parameter 'domainUpdateRequest' is not null or undefined
            assertParamExists('shortUrlsDomainUpdate', 'domainUpdateRequest', domainUpdateRequest)
            const localVarPath = `/api/short-url/domains/{uuid}`
                .replace(`{${"uuid"}}`, encodeURIComponent(String(uuid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(domainUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get list of short urls domains
         * @summary List of domains
         * @param {string} from From date
         * @param {string} to To date
         * @param {number} [page] Get items starting from this page.
         * @param {ShortUrlsDomainsPerPageEnum} [perPage] The number of items in the page. Possible values are from 10 to 500.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        shortUrlsDomains: async (from: string, to: string, page?: number, perPage?: ShortUrlsDomainsPerPageEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'from' is not null or undefined
            assertParamExists('shortUrlsDomains', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('shortUrlsDomains', 'to', to)
            const localVarPath = `/api/short-url/domains`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ExternalAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = to;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ShortDomainsApi - functional programming interface
 * @export
 */
export const ShortDomainsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ShortDomainsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get domain by uuid
         * @param {string} uuid Uuid of entity
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async shortUrlsDomain(uuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ShortUrlsDomain200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.shortUrlsDomain(uuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ShortDomainsApi.shortUrlsDomain']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Add domain
         * @param {DomainStoreRequest} [domainStoreRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async shortUrlsDomainCreate(domainStoreRequest?: DomainStoreRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ShortUrlsDomainCreate201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.shortUrlsDomainCreate(domainStoreRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ShortDomainsApi.shortUrlsDomainCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Remove domain
         * @param {string} uuid Uuid of entity
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async shortUrlsDomainRemove(uuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.shortUrlsDomainRemove(uuid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ShortDomainsApi.shortUrlsDomainRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update domain
         * @param {string} uuid Uuid of entity
         * @param {DomainUpdateRequest} domainUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async shortUrlsDomainUpdate(uuid: string, domainUpdateRequest: DomainUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ShortUrlsDomainUpdate200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.shortUrlsDomainUpdate(uuid, domainUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ShortDomainsApi.shortUrlsDomainUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get list of short urls domains
         * @summary List of domains
         * @param {string} from From date
         * @param {string} to To date
         * @param {number} [page] Get items starting from this page.
         * @param {ShortUrlsDomainsPerPageEnum} [perPage] The number of items in the page. Possible values are from 10 to 500.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async shortUrlsDomains(from: string, to: string, page?: number, perPage?: ShortUrlsDomainsPerPageEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ShortUrlsDomains200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.shortUrlsDomains(from, to, page, perPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ShortDomainsApi.shortUrlsDomains']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ShortDomainsApi - factory interface
 * @export
 */
export const ShortDomainsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ShortDomainsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get domain by uuid
         * @param {string} uuid Uuid of entity
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        shortUrlsDomain(uuid: string, options?: RawAxiosRequestConfig): AxiosPromise<ShortUrlsDomain200Response> {
            return localVarFp.shortUrlsDomain(uuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Add domain
         * @param {DomainStoreRequest} [domainStoreRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        shortUrlsDomainCreate(domainStoreRequest?: DomainStoreRequest, options?: RawAxiosRequestConfig): AxiosPromise<ShortUrlsDomainCreate201Response> {
            return localVarFp.shortUrlsDomainCreate(domainStoreRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Remove domain
         * @param {string} uuid Uuid of entity
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        shortUrlsDomainRemove(uuid: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.shortUrlsDomainRemove(uuid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update domain
         * @param {string} uuid Uuid of entity
         * @param {DomainUpdateRequest} domainUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        shortUrlsDomainUpdate(uuid: string, domainUpdateRequest: DomainUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ShortUrlsDomainUpdate200Response> {
            return localVarFp.shortUrlsDomainUpdate(uuid, domainUpdateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get list of short urls domains
         * @summary List of domains
         * @param {string} from From date
         * @param {string} to To date
         * @param {number} [page] Get items starting from this page.
         * @param {ShortUrlsDomainsPerPageEnum} [perPage] The number of items in the page. Possible values are from 10 to 500.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        shortUrlsDomains(from: string, to: string, page?: number, perPage?: ShortUrlsDomainsPerPageEnum, options?: RawAxiosRequestConfig): AxiosPromise<ShortUrlsDomains200Response> {
            return localVarFp.shortUrlsDomains(from, to, page, perPage, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ShortDomainsApi - interface
 * @export
 * @interface ShortDomainsApi
 */
export interface ShortDomainsApiInterface {
    /**
     * 
     * @summary Get domain by uuid
     * @param {string} uuid Uuid of entity
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShortDomainsApiInterface
     */
    shortUrlsDomain(uuid: string, options?: RawAxiosRequestConfig): AxiosPromise<ShortUrlsDomain200Response>;

    /**
     * 
     * @summary Add domain
     * @param {DomainStoreRequest} [domainStoreRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShortDomainsApiInterface
     */
    shortUrlsDomainCreate(domainStoreRequest?: DomainStoreRequest, options?: RawAxiosRequestConfig): AxiosPromise<ShortUrlsDomainCreate201Response>;

    /**
     * 
     * @summary Remove domain
     * @param {string} uuid Uuid of entity
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShortDomainsApiInterface
     */
    shortUrlsDomainRemove(uuid: string, options?: RawAxiosRequestConfig): AxiosPromise<object>;

    /**
     * 
     * @summary Update domain
     * @param {string} uuid Uuid of entity
     * @param {DomainUpdateRequest} domainUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShortDomainsApiInterface
     */
    shortUrlsDomainUpdate(uuid: string, domainUpdateRequest: DomainUpdateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ShortUrlsDomainUpdate200Response>;

    /**
     * Get list of short urls domains
     * @summary List of domains
     * @param {string} from From date
     * @param {string} to To date
     * @param {number} [page] Get items starting from this page.
     * @param {ShortUrlsDomainsPerPageEnum} [perPage] The number of items in the page. Possible values are from 10 to 500.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShortDomainsApiInterface
     */
    shortUrlsDomains(from: string, to: string, page?: number, perPage?: ShortUrlsDomainsPerPageEnum, options?: RawAxiosRequestConfig): AxiosPromise<ShortUrlsDomains200Response>;

}

/**
 * ShortDomainsApi - object-oriented interface
 * @export
 * @class ShortDomainsApi
 * @extends {BaseAPI}
 */
export class ShortDomainsApi extends BaseAPI implements ShortDomainsApiInterface {
    /**
     * 
     * @summary Get domain by uuid
     * @param {string} uuid Uuid of entity
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShortDomainsApi
     */
    public shortUrlsDomain(uuid: string, options?: RawAxiosRequestConfig) {
        return ShortDomainsApiFp(this.configuration).shortUrlsDomain(uuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Add domain
     * @param {DomainStoreRequest} [domainStoreRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShortDomainsApi
     */
    public shortUrlsDomainCreate(domainStoreRequest?: DomainStoreRequest, options?: RawAxiosRequestConfig) {
        return ShortDomainsApiFp(this.configuration).shortUrlsDomainCreate(domainStoreRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Remove domain
     * @param {string} uuid Uuid of entity
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShortDomainsApi
     */
    public shortUrlsDomainRemove(uuid: string, options?: RawAxiosRequestConfig) {
        return ShortDomainsApiFp(this.configuration).shortUrlsDomainRemove(uuid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update domain
     * @param {string} uuid Uuid of entity
     * @param {DomainUpdateRequest} domainUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShortDomainsApi
     */
    public shortUrlsDomainUpdate(uuid: string, domainUpdateRequest: DomainUpdateRequest, options?: RawAxiosRequestConfig) {
        return ShortDomainsApiFp(this.configuration).shortUrlsDomainUpdate(uuid, domainUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get list of short urls domains
     * @summary List of domains
     * @param {string} from From date
     * @param {string} to To date
     * @param {number} [page] Get items starting from this page.
     * @param {ShortUrlsDomainsPerPageEnum} [perPage] The number of items in the page. Possible values are from 10 to 500.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShortDomainsApi
     */
    public shortUrlsDomains(from: string, to: string, page?: number, perPage?: ShortUrlsDomainsPerPageEnum, options?: RawAxiosRequestConfig) {
        return ShortDomainsApiFp(this.configuration).shortUrlsDomains(from, to, page, perPage, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const ShortUrlsDomainsPerPageEnum = {
    NUMBER_10: 10,
    NUMBER_20: 20,
    NUMBER_50: 50,
    NUMBER_100: 100,
    NUMBER_200: 200,
    NUMBER_500: 500
} as const;
export type ShortUrlsDomainsPerPageEnum = typeof ShortUrlsDomainsPerPageEnum[keyof typeof ShortUrlsDomainsPerPageEnum];
