/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BalanceSchema } from './balance-schema';

/**
 * 
 * @export
 * @interface AccountBalance200Response
 */
export interface AccountBalance200Response {
    /**
     * 
     * @type {BalanceSchema}
     * @memberof AccountBalance200Response
     */
    'data'?: BalanceSchema;
}

