/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Sms } from './sms';

/**
 * The object contains information for sending a message via an alternative SMS channel in case of non-delivery with primary channel
 * @export
 * @interface AlternativeChannel
 */
export interface AlternativeChannel {
    /**
     * 
     * @type {Sms}
     * @memberof AlternativeChannel
     */
    'sms'?: Sms;
}

