/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BalanceSchema
 */
export interface BalanceSchema {
    /**
     * Current amount of funds on the account balance
     * @type {number}
     * @memberof BalanceSchema
     */
    'balance'?: number;
    /**
     * The currency code of the account. Specified according to the ISO-4217 standard
     * @type {string}
     * @memberof BalanceSchema
     */
    'currency'?: string;
    /**
     * Available credit limit of the account by the postpay type
     * @type {number}
     * @memberof BalanceSchema
     */
    'credit'?: number;
}

