/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * campaign status usually: done
 * @export
 * @enum {string}
 */

export const CampaignStatus = {
    Creation: 'creation',
    Scheduled: 'scheduled',
    Sending: 'sending',
    Done: 'done',
    Paused: 'paused',
    Stopped: 'stopped',
    Spam: 'spam',
    Moderation: 'moderation'
} as const;

export type CampaignStatus = typeof CampaignStatus[keyof typeof CampaignStatus];



