/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CampaignStatus } from './campaign-status';
// May contain unused imports in some cases
// @ts-ignore
import type { MessageType } from './message-type';
// May contain unused imports in some cases
// @ts-ignore
import type { StatisticsShort } from './statistics-short';

/**
 * Main campaign properties
 * @export
 * @interface CampaignSchema
 */
export interface CampaignSchema {
    /**
     * campaign unique identifier
     * @type {number}
     * @memberof CampaignSchema
     */
    'id'?: number;
    /**
     * campaign auto generated name
     * @type {string}
     * @memberof CampaignSchema
     */
    'name'?: string;
    /**
     * Sender’s name: from 3 to 11 characters for the sender’s alphanumeric name (Latin letters, symbols, numbers, spaces); 3 to 15 characters for the sender’s numeric name. To setup senders visit the [account](https://app.bsg.world/sms/senders)
     * @type {string}
     * @memberof CampaignSchema
     */
    'sender'?: string;
    /**
     * 
     * @type {CampaignStatus}
     * @memberof CampaignSchema
     */
    'status'?: CampaignStatus;
    /**
     * 
     * @type {MessageType}
     * @memberof CampaignSchema
     */
    'message_type'?: MessageType;
    /**
     * Start sending the messages at
     * @type {string}
     * @memberof CampaignSchema
     */
    'start_at'?: string;
    /**
     * Real time when sending the messages starts
     * @type {string}
     * @memberof CampaignSchema
     */
    'real_start_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CampaignSchema
     */
    'finished_at'?: string | null;
    /**
     * Date when the item was created in the system ― set by the system automatically. Display format ― Y-m-d H:i:s
     * @type {string}
     * @memberof CampaignSchema
     */
    'created_at'?: string;
    /**
     * 
     * @type {StatisticsShort}
     * @memberof CampaignSchema
     */
    'statistics'?: StatisticsShort;
    /**
     * estimate campaign cost  **Please note:** price defined only as the response to create campaign or calculate price requests
     * @type {number}
     * @memberof CampaignSchema
     */
    'calculated_price'?: number | null;
    /**
     * The currency code of the account. Specified according to the ISO-4217 standard
     * @type {string}
     * @memberof CampaignSchema
     */
    'currency'?: string;
}



