/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CampaignPrice422Response
 */
export interface CampaignPrice422Response {
    /**
     * The given data was invalid. It can be one of the following:  - **The given data was invalid.** Detailed error is described in errors field. - **Tariff not found**  This error can occur when the tariff identifier is specified incorrectly or the specified tariff is not present in the system. Please ensure that you are using the correct tariff identifier and try again. For more information please visit the [account prices](https://app.bsg.world/prices/sms)  
     * @type {string}
     * @memberof CampaignPrice422Response
     */
    'message'?: string;
    /**
     * errors
     * @type {Array<any>}
     * @memberof CampaignPrice422Response
     */
    'errors'?: Array<any>;
}

