/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CampaignPrice200Response
 */
export interface CampaignPrice200Response {
    /**
     * estimate campaign cost  **Please note:** price defined only as the response to create campaign or calculate price requests
     * @type {number}
     * @memberof CampaignPrice200Response
     */
    'price'?: number | null;
    /**
     * The currency code of the account. Specified according to the ISO-4217 standard
     * @type {string}
     * @memberof CampaignPrice200Response
     */
    'currency'?: string;
}

