/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CampaignPriceRequestMessagesItem } from './campaign-price-request-messages-item';

/**
 * 
 * @export
 * @interface CampaignPriceRequest
 */
export interface CampaignPriceRequest {
    /**
     * Sender’s name: from 3 to 11 characters for the sender’s alphanumeric name (Latin letters, symbols, numbers, spaces); 3 to 15 characters for the sender’s numeric name. To setup senders visit the [account](https://app.bsg.world/sms/senders)
     * @type {string}
     * @memberof CampaignPriceRequest
     */
    'sender': string;
    /**
     * Message text to send
     * @type {string}
     * @memberof CampaignPriceRequest
     */
    'text': string;
    /**
     * Tariff code null by default. Your can pass specified one if you have several. For more information please visit the [account prices](https://app.bsg.world/prices/sms)
     * @type {number}
     * @memberof CampaignPriceRequest
     */
    'tariff_code'?: number;
    /**
     * 
     * @type {Set<number>}
     * @memberof CampaignPriceRequest
     */
    'groups'?: Set<number>;
    /**
     * 
     * @type {Array<CampaignPriceRequestMessagesItem>}
     * @memberof CampaignPriceRequest
     */
    'messages'?: Array<CampaignPriceRequestMessagesItem>;
}

