/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CampaignStop422Response
 */
export interface CampaignStop422Response {
    /**
     * Invalid campaign status  The campaign must be in one of following status to be able to stop: \"scheduled\", \"sending\", \"paused\", \"moderation\"
     * @type {string}
     * @memberof CampaignStop422Response
     */
    'message'?: string;
    /**
     * errors
     * @type {Array<any>}
     * @memberof CampaignStop422Response
     */
    'errors'?: Array<any>;
}

