/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Media } from './media';
// May contain unused imports in some cases
// @ts-ignore
import type { Suggestion } from './suggestion';

/**
 * Either \"media\" or \"text\" is required.
 * @export
 * @interface Card
 */
export interface Card {
    /**
     * Message title
     * @type {string}
     * @memberof Card
     */
    'title'?: string;
    /**
     * It is specified only for the “text” message type. RCS message text is up to 1000 characters. Can contain emojis (character count for emojis according to UTF-16 code points. Simple emojis take 2 code points, complex emojis take 4, Cyrillic emojis take 1). If the message contains a link in the format http://nosms.cc/XXXX, the System will generate an Unsubscribe link while sending the message  **Please note:** If the message contains a media object, the text parameter is optional and can be omitted
     * @type {string}
     * @memberof Card
     */
    'text'?: string;
    /**
     * 
     * @type {Media}
     * @memberof Card
     */
    'media'?: Media;
    /**
     * An array of objects containing information about nested buttons. Only up to 2 buttons can be added to a card.
     * @type {Array<Suggestion>}
     * @memberof Card
     */
    'suggestions'?: Array<Suggestion>;
}

