/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClickResource
 */
export interface ClickResource {
    /**
     * click unique uuid
     * @type {string}
     * @memberof ClickResource
     */
    'id'?: string;
    /**
     * Language of user browser
     * @type {string}
     * @memberof ClickResource
     */
    'browser_language'?: string;
    /**
     * User country detected by geo ip
     * @type {string}
     * @memberof ClickResource
     */
    'country_code'?: string | null;
    /**
     * We use some heuristics to determine is it real human or looks like bot
     * @type {boolean}
     * @memberof ClickResource
     */
    'is_human'?: boolean;
    /**
     * We use combination of ip address user-agent cookies and so on to account the same user just once
     * @type {boolean}
     * @memberof ClickResource
     */
    'is_unique'?: boolean;
    /**
     * Status code returned by GET original link when redirecting the user
     * @type {number}
     * @memberof ClickResource
     */
    'http_status'?: number;
    /**
     * Http method used by user when click on short link
     * @type {string}
     * @memberof ClickResource
     */
    'http_method'?: string;
    /**
     * Date and time of click
     * @type {string}
     * @memberof ClickResource
     */
    'created_at'?: string;
    /**
     * User-agent of first click
     * @type {string}
     * @memberof ClickResource
     */
    'user_agent'?: string;
    /**
     * Client IP address of first click
     * @type {string}
     * @memberof ClickResource
     */
    'client_ip'?: string;
    /**
     * User browser detected from user-agent
     * @type {string}
     * @memberof ClickResource
     */
    'browser'?: string;
    /**
     * source page from witch user click on short link
     * @type {string}
     * @memberof ClickResource
     */
    'referrer_url'?: string | null;
    /**
     * User city detected by geo ip
     * @type {string}
     * @memberof ClickResource
     */
    'city'?: string | null;
    /**
     * User device operation system detected from user-agent
     * @type {string}
     * @memberof ClickResource
     */
    'device_os'?: string | null;
    /**
     * short link url that can be used to redirect to original link
     * @type {string}
     * @memberof ClickResource
     */
    'short_link'?: string;
    /**
     * Original link where to short link will redirect
     * @type {string}
     * @memberof ClickResource
     */
    'original_link'?: string;
    /**
     * message id for short links created as part of [sms campaign](#tag/Campaign-SMS)
     * @type {number}
     * @memberof ClickResource
     */
    'message_id'?: number | null;
    /**
     * Phone number without leading plus. For short links created as part of [sms campaign](#tag/Campaign-SMS)
     * @type {number}
     * @memberof ClickResource
     */
    'phone_number'?: number | null;
}

