/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Parameter } from './parameter';

/**
 * 
 * @export
 * @interface Components
 */
export interface Components {
    /**
     * 
     * @type {string}
     * @memberof Components
     */
    'type': ComponentsTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Components
     */
    'sub_type'?: ComponentsSubTypeEnum | null;
    /**
     * 
     * @type {string}
     * @memberof Components
     */
    'index'?: string | null;
    /**
     * 
     * @type {Array<Parameter>}
     * @memberof Components
     */
    'parameters'?: Array<Parameter>;
}

export const ComponentsTypeEnum = {
    Header: 'header',
    Body: 'body',
    Button: 'button'
} as const;

export type ComponentsTypeEnum = typeof ComponentsTypeEnum[keyof typeof ComponentsTypeEnum];
export const ComponentsSubTypeEnum = {
    QuickReply: 'quick_reply',
    Url: 'url',
    Catalog: 'catalog'
} as const;

export type ComponentsSubTypeEnum = typeof ComponentsSubTypeEnum[keyof typeof ComponentsSubTypeEnum];


