/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContactSchema } from './contact-schema';

/**
 * 
 * @export
 * @interface Contact200Response
 */
export interface Contact200Response {
    /**
     * 
     * @type {ContactSchema}
     * @memberof Contact200Response
     */
    'data'?: ContactSchema;
}

