/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContactListUpdateRequest
 */
export interface ContactListUpdateRequest {
    /**
     * Name of the contact list
     * @type {string}
     * @memberof ContactListUpdateRequest
     */
    'name': string;
    /**
     * Description of the contact list
     * @type {string}
     * @memberof ContactListUpdateRequest
     */
    'description'?: string | null;
    /**
     * Specifies whether the contact list is a default one
     * @type {boolean}
     * @memberof ContactListUpdateRequest
     */
    'default'?: boolean | null;
}

