/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContactGroupSchema
 */
export interface ContactGroupSchema {
    /**
     * ID of the contact list. generated automatically when creating a [contact list](#operation/contact_list_create)
     * @type {number}
     * @memberof ContactGroupSchema
     */
    'id'?: number;
    /**
     * Name of the contact list
     * @type {string}
     * @memberof ContactGroupSchema
     */
    'name'?: string;
    /**
     * Description of the contact list
     * @type {string}
     * @memberof ContactGroupSchema
     */
    'description'?: string | null;
    /**
     * Specifies whether the contact list is a default one
     * @type {boolean}
     * @memberof ContactGroupSchema
     */
    'default'?: boolean | null;
    /**
     * Date when the item was created in the system ― set by the system automatically. Display format ― Y-m-d H:i:s
     * @type {string}
     * @memberof ContactGroupSchema
     */
    'created_at'?: string;
    /**
     * Total number of contacts in this list
     * @type {number}
     * @memberof ContactGroupSchema
     */
    'items'?: number;
    /**
     * The number of contacts from the list that are in the stop list of SMS and Viber
     * @type {number}
     * @memberof ContactGroupSchema
     */
    'stop_list_count'?: number;
}

