/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContactUpdate422Response
 */
export interface ContactUpdate422Response {
    /**
     * It may be one of the following errors:  - **Phone number is already exist in contact book** - There are exists another contact with the same phone number, use that instead of change phone of this   - **Invalid contact id** - Pass correct contact id  - **Invalid phone number format** - Pass correct phone number 
     * @type {string}
     * @memberof ContactUpdate422Response
     */
    'message'?: string;
    /**
     * errors
     * @type {Array<any>}
     * @memberof ContactUpdate422Response
     */
    'errors'?: Array<any>;
}

