/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContactFieldUpdateRequestOption1
 */
export interface ContactFieldUpdateRequestOption1 {
    /**
     * The name of the custom field for the contacts
     * @type {string}
     * @memberof ContactFieldUpdateRequestOption1
     */
    'name'?: string;
}

