/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContactFieldUpdateRequestOption1 } from './contact-field-update-request-option1';
// May contain unused imports in some cases
// @ts-ignore
import type { ContactFieldUpdateRequestOption2 } from './contact-field-update-request-option2';
// May contain unused imports in some cases
// @ts-ignore
import type { ContactFieldUpdateRequestOption3 } from './contact-field-update-request-option3';

/**
 * 
 * @export
 * @interface ContactFieldUpdateRequest
 */
export interface ContactFieldUpdateRequest {
    /**
     * The name of the custom field for the contacts
     * @type {string}
     * @memberof ContactFieldUpdateRequest
     */
    'name'?: string;
    /**
     * Description of the custom contact field
     * @type {string}
     * @memberof ContactFieldUpdateRequest
     */
    'description'?: string;
    /**
     * Whether the field is displayed: true or false value
     * @type {boolean}
     * @memberof ContactFieldUpdateRequest
     */
    'is_visible'?: boolean;
}

