/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContactsSearch200ResponseMetaPage } from './contacts-search200-response-meta-page';
// May contain unused imports in some cases
// @ts-ignore
import type { ContactsSearch200ResponseMetaSearch } from './contacts-search200-response-meta-search';

/**
 * Information about search criteria and total results count
 * @export
 * @interface ContactsSearch200ResponseMeta
 */
export interface ContactsSearch200ResponseMeta {
    /**
     * 
     * @type {ContactsSearch200ResponseMetaPage}
     * @memberof ContactsSearch200ResponseMeta
     */
    'page'?: ContactsSearch200ResponseMetaPage;
    /**
     * 
     * @type {ContactsSearch200ResponseMetaSearch}
     * @memberof ContactsSearch200ResponseMeta
     */
    'search'?: ContactsSearch200ResponseMetaSearch;
}

