/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * contains embedded custom fields data
 * @export
 * @interface ContactFieldValuePair
 */
export interface ContactFieldValuePair {
    /**
     * Custom field ID
     * @type {number}
     * @memberof ContactFieldValuePair
     */
    'id'?: number;
    /**
     * Custom field data
     * @type {string}
     * @memberof ContactFieldValuePair
     */
    'value'?: string;
}

