/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContactFieldValuePair } from './contact-field-value-pair';
// May contain unused imports in some cases
// @ts-ignore
import type { ContactGroupSchema } from './contact-group-schema';

/**
 * 
 * @export
 * @interface ContactUpdateRequest
 */
export interface ContactUpdateRequest {
    /**
     * Contact’s phone number
     * @type {number}
     * @memberof ContactUpdateRequest
     */
    'phone': number;
    /**
     * contains embedded data of the list where the contact is added
     * @type {Array<ContactGroupSchema>}
     * @memberof ContactUpdateRequest
     */
    'groups'?: Array<ContactGroupSchema>;
    /**
     * Array of custom fields values
     * @type {Array<ContactFieldValuePair>}
     * @memberof ContactUpdateRequest
     */
    'fields'?: Array<ContactFieldValuePair>;
}

