/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContactSchema } from './contact-schema';

/**
 * 
 * @export
 * @interface Contacts200Response
 */
export interface Contacts200Response {
    /**
     * list of contacts
     * @type {Array<ContactSchema>}
     * @memberof Contacts200Response
     */
    'data'?: Array<ContactSchema>;
    /**
     * Total items count at all of the pages
     * @type {number}
     * @memberof Contacts200Response
     */
    'total'?: number;
}

