/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContactSchema } from './contact-schema';
// May contain unused imports in some cases
// @ts-ignore
import type { ContactsSearch200ResponseMeta } from './contacts-search200-response-meta';

/**
 * 
 * @export
 * @interface ContactsSearch200Response
 */
export interface ContactsSearch200Response {
    /**
     * List of searched contacts
     * @type {Array<ContactSchema>}
     * @memberof ContactsSearch200Response
     */
    'data'?: Array<ContactSchema>;
    /**
     * 
     * @type {ContactsSearch200ResponseMeta}
     * @memberof ContactsSearch200Response
     */
    'meta'?: ContactsSearch200ResponseMeta;
}

