/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContactFieldUpdateRequestOption3
 */
export interface ContactFieldUpdateRequestOption3 {
    /**
     * Whether the field is displayed: true or false value
     * @type {boolean}
     * @memberof ContactFieldUpdateRequestOption3
     */
    'is_visible'?: boolean;
}

