/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Contact422Response
 */
export interface Contact422Response {
    /**
     * Invalid contact id
     * @type {string}
     * @memberof Contact422Response
     */
    'message'?: string;
    /**
     * errors
     * @type {Array<any>}
     * @memberof Contact422Response
     */
    'errors'?: Array<any>;
}

