/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContactListSearch200ResponseMetaPage } from './contact-list-search200-response-meta-page';
// May contain unused imports in some cases
// @ts-ignore
import type { ContactListSearch200ResponseMetaSearch } from './contact-list-search200-response-meta-search';

/**
 * Information about search criteria and total results count
 * @export
 * @interface ContactListSearch200ResponseMeta
 */
export interface ContactListSearch200ResponseMeta {
    /**
     * 
     * @type {ContactListSearch200ResponseMetaPage}
     * @memberof ContactListSearch200ResponseMeta
     */
    'page'?: ContactListSearch200ResponseMetaPage;
    /**
     * 
     * @type {ContactListSearch200ResponseMetaSearch}
     * @memberof ContactListSearch200ResponseMeta
     */
    'search'?: ContactListSearch200ResponseMetaSearch;
}

