/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContactFieldType } from './contact-field-type';

/**
 * 
 * @export
 * @interface ContactFieldCreateRequest
 */
export interface ContactFieldCreateRequest {
    /**
     * The name of the custom field for the contacts
     * @type {string}
     * @memberof ContactFieldCreateRequest
     */
    'name': string;
    /**
     * Description of the custom contact field
     * @type {string}
     * @memberof ContactFieldCreateRequest
     */
    'description'?: string;
    /**
     * Whether the field is displayed: true or false value
     * @type {boolean}
     * @memberof ContactFieldCreateRequest
     */
    'is_visible'?: boolean;
    /**
     * 
     * @type {ContactFieldType}
     * @memberof ContactFieldCreateRequest
     */
    'type': ContactFieldType;
}



