/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Fields for search: name, items, date, description, phone, id
 * @export
 * @enum {string}
 */

export const ContactGroupSearchField = {
    Id: 'id',
    Name: 'name',
    Items: 'items',
    CreatedAt: 'created_at',
    Phone: 'phone',
    Description: 'description'
} as const;

export type ContactGroupSearchField = typeof ContactGroupSearchField[keyof typeof ContactGroupSearchField];



