/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OperatorSchema } from './operator-schema';

/**
 * 
 * @export
 * @interface CorePriceSchema
 */
export interface CorePriceSchema {
    /**
     * 
     * @type {number}
     * @memberof CorePriceSchema
     */
    'tariff'?: number;
    /**
     * 
     * @type {string}
     * @memberof CorePriceSchema
     */
    'limitation_info'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CorePriceSchema
     */
    'country_id'?: string;
    /**
     * 
     * @type {Array<OperatorSchema>}
     * @memberof CorePriceSchema
     */
    'operators'?: Array<OperatorSchema>;
}

