/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DateTimeParameter
 */
export interface DateTimeParameter {
    /**
     * Default text. For Cloud API, we always use the fallback value, and we do not attempt to localize using other optional fields
     * @type {string}
     * @memberof DateTimeParameter
     */
    'fallback_value': string;
}

