/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ShortDomainSlugType } from './short-domain-slug-type';

/**
 * 
 * @export
 * @interface DomainUpdateRequest
 */
export interface DomainUpdateRequest {
    /**
     * Url to redirect if original link return status 404 not found
     * @type {string}
     * @memberof DomainUpdateRequest
     */
    'not_found_page'?: string;
    /**
     * 
     * @type {ShortDomainSlugType}
     * @memberof DomainUpdateRequest
     */
    'slug_type'?: ShortDomainSlugType;
    /**
     * This domain is default for generating short links
     * @type {boolean}
     * @memberof DomainUpdateRequest
     */
    'is_default'?: boolean;
}



