/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetInternalCurrencies200ResponseDataItem
 */
export interface GetInternalCurrencies200ResponseDataItem {
    /**
     * 
     * @type {string}
     * @memberof GetInternalCurrencies200ResponseDataItem
     */
    'id'?: string;
    /**
     * EUR exchange rate
     * @type {number}
     * @memberof GetInternalCurrencies200ResponseDataItem
     */
    'ratio'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetInternalCurrencies200ResponseDataItem
     */
    'nominal'?: number;
    /**
     * 
     * @type {any}
     * @memberof GetInternalCurrencies200ResponseDataItem
     */
    'date'?: any;
}

