/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WstPriceSchema } from './wst-price-schema';

/**
 * 
 * @export
 * @interface GetInternalWstPrices200Response
 */
export interface GetInternalWstPrices200Response {
    /**
     * 
     * @type {Array<WstPriceSchema>}
     * @memberof GetInternalWstPrices200Response
     */
    'data': Array<WstPriceSchema>;
}

