/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetMessages200ResponseMeta } from './get-messages200-response-meta';
// May contain unused imports in some cases
// @ts-ignore
import type { MessageApiSchema } from './message-api-schema';

/**
 * 
 * @export
 * @interface GetMessages200Response
 */
export interface GetMessages200Response {
    /**
     * 
     * @type {Array<MessageApiSchema>}
     * @memberof GetMessages200Response
     */
    'data'?: Array<MessageApiSchema>;
    /**
     * 
     * @type {GetMessages200ResponseMeta}
     * @memberof GetMessages200Response
     */
    'meta'?: GetMessages200ResponseMeta;
}

