/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IndividualMessageData
 */
export interface IndividualMessageData {
    /**
     * Phone number without leading plus, just digits
     * @type {number}
     * @memberof IndividualMessageData
     */
    'phone': number;
    /**
     * SMS text, max length is 765 chars for GSM 7-bit encoding (Latin), and 355 for UCS-2
     * @type {string}
     * @memberof IndividualMessageData
     */
    'text': string;
    /**
     * Sender’s name: from 3 to 11 characters for the sender’s alphanumeric name (Latin letters, symbols, numbers, spaces); 3 to 15 characters for the sender’s numeric name. To setup senders visit the [account](https://app.bsg.world/sms/senders)
     * @type {string}
     * @memberof IndividualMessageData
     */
    'sender': string;
    /**
     * Tariff code null by default. Your can pass specified one if you have several. For more information please visit the [account prices](https://app.bsg.world/prices/sms)
     * @type {number}
     * @memberof IndividualMessageData
     */
    'tariff_code'?: number;
    /**
     * external unique ID. String up to 32 characters containing only alpha numeric characters.  **Please note:** messages with duplicate reference_id will be rejected
     * @type {string}
     * @memberof IndividualMessageData
     */
    'reference_id'?: string;
    /**
     * apply transliteration to sms text if it necessary
     * @type {boolean}
     * @memberof IndividualMessageData
     */
    'transliterate'?: boolean;
}

