/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Inline
 */
export interface Inline {
    /**
     * A variable representing the name or identifier of the inline attachment
     * @type {string}
     * @memberof Inline
     */
    'name': string;
    /**
     * The content identifier (links the inline attachment to the email body)
     * @type {string}
     * @memberof Inline
     */
    'cid': string;
    /**
     * MIME content type
     * @type {string}
     * @memberof Inline
     */
    'contentType'?: string;
    /**
     * The base64-encoded content of the inline attachment
     * @type {string}
     * @memberof Inline
     */
    'content': string;
}

