/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MessageApiSchemaAlternativeChannelsOneOf0Sms
 */
export interface MessageApiSchemaAlternativeChannelsOneOf0Sms {
    /**
     * 
     * @type {number}
     * @memberof MessageApiSchemaAlternativeChannelsOneOf0Sms
     */
    'parts'?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof MessageApiSchemaAlternativeChannelsOneOf0Sms
     */
    'id'?: Array<number>;
}

