/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MessageApiSchemaAlternativeChannelsOneOf1Viber } from './message-api-schema-alternative-channels-one-of1-viber';

/**
 * 
 * @export
 * @interface MessageApiSchemaAlternativeChannelsOption2
 */
export interface MessageApiSchemaAlternativeChannelsOption2 {
    /**
     * 
     * @type {MessageApiSchemaAlternativeChannelsOneOf1Viber}
     * @memberof MessageApiSchemaAlternativeChannelsOption2
     */
    'viber'?: MessageApiSchemaAlternativeChannelsOneOf1Viber;
}

