/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MessageApiSchemaAlternativeChannels } from './message-api-schema-alternative-channels';
// May contain unused imports in some cases
// @ts-ignore
import type { MessagePriceObject } from './message-price-object';
// May contain unused imports in some cases
// @ts-ignore
import type { MessageSource } from './message-source';
// May contain unused imports in some cases
// @ts-ignore
import type { MessageStatus } from './message-status';
// May contain unused imports in some cases
// @ts-ignore
import type { MessageType } from './message-type';
// May contain unused imports in some cases
// @ts-ignore
import type { Options } from './options';

/**
 * 
 * @export
 * @interface MessageApiSchema
 */
export interface MessageApiSchema {
    /**
     * Message ID – a unique identifier automatically generated on the Platform when the message is created
     * @type {number}
     * @memberof MessageApiSchema
     */
    'id'?: number;
    /**
     * campaign unique identifier
     * @type {number}
     * @memberof MessageApiSchema
     */
    'campaign_id'?: number;
    /**
     * external unique ID. String up to 32 characters containing only alpha numeric characters.  **Please note:** messages with duplicate reference_id will be rejected
     * @type {string}
     * @memberof MessageApiSchema
     */
    'reference_id'?: string;
    /**
     * 
     * @type {MessageType}
     * @memberof MessageApiSchema
     */
    'type'?: MessageType;
    /**
     * 
     * @type {MessageSource}
     * @memberof MessageApiSchema
     */
    'source'?: MessageSource;
    /**
     * Message text to send
     * @type {string}
     * @memberof MessageApiSchema
     */
    'text'?: string;
    /**
     * Phone number without leading plus, just digits
     * @type {number}
     * @memberof MessageApiSchema
     */
    'phone'?: number;
    /**
     * validity time in hours. The default is 72 hours. Integer from 1 to 72
     * @type {number}
     * @memberof MessageApiSchema
     */
    'validity'?: number;
    /**
     * 
     * @type {MessageStatus}
     * @memberof MessageApiSchema
     */
    'status'?: MessageStatus;
    /**
     * 
     * @type {MessagePriceObject}
     * @memberof MessageApiSchema
     */
    'amount'?: MessagePriceObject;
    /**
     * Sender name.   Up to 11 Latin letters or digits, up to 15 – only digits. To setup senders visit the [account](https://app.bsg.world/sms/senders) or use [sender api](#tag/Senders)
     * @type {string}
     * @memberof MessageApiSchema
     */
    'sender'?: string;
    /**
     * Date when the item was created in the system ― set by the system automatically. Display format ― Y-m-d H:i:s
     * @type {string}
     * @memberof MessageApiSchema
     */
    'created_at'?: string;
    /**
     * Date and time of sending the message
     * @type {string}
     * @memberof MessageApiSchema
     */
    'sent_at'?: string | null;
    /**
     * Date and time of receipt of the delivery report response
     * @type {string}
     * @memberof MessageApiSchema
     */
    'delivered_at'?: string | null;
    /**
     * Country code according to ISO 3166-1 alpha-2 standard
     * @type {string}
     * @memberof MessageApiSchema
     */
    'country'?: string;
    /**
     * 
     * @type {number}
     * @memberof MessageApiSchema
     */
    'parts'?: number;
    /**
     * 
     * @type {Options}
     * @memberof MessageApiSchema
     */
    'rcs_options'?: Options;
    /**
     * 
     * @type {MessageApiSchemaAlternativeChannels}
     * @memberof MessageApiSchema
     */
    'alternative_channels'?: MessageApiSchemaAlternativeChannels | null;
}



