/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Message price value and currency
 * @export
 * @interface MessagePriceObject
 */
export interface MessagePriceObject {
    /**
     * Message price
     * @type {number}
     * @memberof MessagePriceObject
     */
    'value'?: number;
    /**
     * The currency code of the account. Specified according to the ISO-4217 standard
     * @type {string}
     * @memberof MessagePriceObject
     */
    'currency'?: string;
}

