/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The source how message was sent by  - rest - by this api - web - by web interface of [personal account](https://app.bsg.world) - smpp - by smpp connection - 2fa - sent by 2fa - voicebot - sent by voicebot - twoway - two way sms by interface - twoway_api - two way sms by api - xml - service messages     
 * @export
 * @enum {string}
 */

export const MessageSource = {
    Web: 'web',
    Rest: 'rest',
    Smpp: 'smpp',
    Xml: 'xml',
    Twoway: 'twoway',
    TwowayApi: 'twoway_api',
    _2fa: '2fa',
    Voicebot: 'voicebot'
} as const;

export type MessageSource = typeof MessageSource[keyof typeof MessageSource];



