/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MessageApiSchemaAlternativeChannelsOneOf0Sms } from './message-api-schema-alternative-channels-one-of0-sms';
// May contain unused imports in some cases
// @ts-ignore
import type { MessageApiSchemaAlternativeChannelsOneOf1Viber } from './message-api-schema-alternative-channels-one-of1-viber';
// May contain unused imports in some cases
// @ts-ignore
import type { MessageApiSchemaAlternativeChannelsOption1 } from './message-api-schema-alternative-channels-option1';
// May contain unused imports in some cases
// @ts-ignore
import type { MessageApiSchemaAlternativeChannelsOption2 } from './message-api-schema-alternative-channels-option2';

/**
 * @type MessageApiSchemaAlternativeChannels
 * @export
 */
export type MessageApiSchemaAlternativeChannels = MessageApiSchemaAlternativeChannelsOption1 | MessageApiSchemaAlternativeChannelsOption2;


