/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Message status. Possible values:delivered – the message was sent;accepted – message accepted for sending;undelivered – the message was not delivered.
 * @export
 * @enum {string}
 */

export const OtpMessageStatus = {
    Sent: 'sent',
    Accepted: 'accepted'
} as const;

export type OtpMessageStatus = typeof OtpMessageStatus[keyof typeof OtpMessageStatus];



