/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OtpTemplateDelete404Response
 */
export interface OtpTemplateDelete404Response {
    /**
     * TwoFA Service error.
     * @type {string}
     * @memberof OtpTemplateDelete404Response
     */
    'message'?: string;
    /**
     * It may be one of the following: - **Template not found** This error can occur when the template identifier is specified incorrectly or the specified template is not present in the system. Please ensure that you are using the correct template identifier and try again. 
     * @type {Array<string>}
     * @memberof OtpTemplateDelete404Response
     */
    'errors'?: Array<string>;
}

