/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TwoFaTemplateResource } from './two-fa-template-resource';

/**
 * 
 * @export
 * @interface OtpTemplateList200ResponseData
 */
export interface OtpTemplateList200ResponseData {
    /**
     * 
     * @type {Array<TwoFaTemplateResource>}
     * @memberof OtpTemplateList200ResponseData
     */
    'list'?: Array<TwoFaTemplateResource>;
    /**
     * A total number of templates that meet the search conditions.
     * @type {number}
     * @memberof OtpTemplateList200ResponseData
     */
    'total'?: number;
}

