/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Authentication status. Possible values: pending (authentication session successfully created and pending)
 * @export
 * @enum {string}
 */

export const OtpStatus = {
    Pending: 'pending',
    Verified: 'verified',
    Failed: 'failed',
    Canceled: 'canceled',
    Expired: 'expired'
} as const;

export type OtpStatus = typeof OtpStatus[keyof typeof OtpStatus];



