/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Status of the template. After template creation, the status of the template will always be “requested.”
 * @export
 * @enum {string}
 */

export const OtpTemplateStatus = {
    Requested: 'requested',
    Approved: 'approved',
    Rejected: 'rejected',
    Deleted: 'deleted'
} as const;

export type OtpTemplateStatus = typeof OtpTemplateStatus[keyof typeof OtpTemplateStatus];



