/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OtpList200ResponseData } from './otp-list200-response-data';

/**
 * 
 * @export
 * @interface OtpList200Response
 */
export interface OtpList200Response {
    /**
     * 
     * @type {OtpList200ResponseData}
     * @memberof OtpList200Response
     */
    'data': OtpList200ResponseData;
}

