/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Parameter
 */
export interface Parameter {
    /**
     * 
     * @type {string}
     * @memberof Parameter
     */
    'type': ParameterTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Parameter
     */
    'text'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Parameter
     */
    'payload'?: string | null;
}

export const ParameterTypeEnum = {
    Text: 'text',
    Payload: 'payload'
} as const;

export type ParameterTypeEnum = typeof ParameterTypeEnum[keyof typeof ParameterTypeEnum];


