/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * RCS click callback object
 * @export
 * @interface RcsClickCallback
 */
export interface RcsClickCallback {
    /**
     * Message ID – a unique identifier automatically generated on the Platform when the message is created
     * @type {number}
     * @memberof RcsClickCallback
     */
    'id'?: number;
    /**
     * external unique ID. String up to 32 characters containing only alpha numeric characters.  **Please note:** messages with duplicate reference_id will be rejected
     * @type {string}
     * @memberof RcsClickCallback
     */
    'reference'?: string;
    /**
     * Phone number without leading plus, just digits
     * @type {string}
     * @memberof RcsClickCallback
     */
    'msisdn'?: string;
    /**
     * Text on clicked button from suggestions
     * @type {string}
     * @memberof RcsClickCallback
     */
    'text'?: string;
    /**
     * postback_data field value from suggestion button object
     * @type {string}
     * @memberof RcsClickCallback
     */
    'postback'?: string;
    /**
     * Date when the item was created in the system ― set by the system automatically. Display format ― Y-m-d H:i:s
     * @type {string}
     * @memberof RcsClickCallback
     */
    'time_click'?: string;
}

