/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CampaignSchema } from './campaign-schema';

/**
 * 
 * @export
 * @interface RcsSendGroups200Response
 */
export interface RcsSendGroups200Response {
    /**
     * 
     * @type {CampaignSchema}
     * @memberof RcsSendGroups200Response
     */
    'data'?: CampaignSchema;
}

