/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SearchCampaignResourceMetaPage
 */
export interface SearchCampaignResourceMetaPage {
    /**
     * Total items count at all of the pages
     * @type {number}
     * @memberof SearchCampaignResourceMetaPage
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchCampaignResourceMetaPage
     */
    'limit'?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchCampaignResourceMetaPage
     */
    'offset'?: number;
}

