/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Options } from './options';
// May contain unused imports in some cases
// @ts-ignore
import type { SendRcsCampaignGroupsAlternativeChannel } from './send-rcs-campaign-groups-alternative-channel';

/**
 * 
 * @export
 * @interface SendRcsCampaignGroups
 */
export interface SendRcsCampaignGroups {
    /**
     * An array of lists (list id) with contacts from the address book to which RCS campaigns are to be sent. id of the lists can be obtained: using the Get [lists API](#tag/Contact-List) in your account [Contact Book → Lists](https://app.bsg.world/addressbook/lists)
     * @type {Array<number>}
     * @memberof SendRcsCampaignGroups
     */
    'groups': Array<number>;
    /**
     * The name of the agent used to send the rcs message
     * @type {string}
     * @memberof SendRcsCampaignGroups
     */
    'sender': string;
    /**
     * Tariff code null by default. Your can pass specified one if you have several. For more information please visit the [account prices](https://app.bsg.world/prices/sms)
     * @type {number}
     * @memberof SendRcsCampaignGroups
     */
    'tariff_code'?: number;
    /**
     * validity time in hours. The default is 72 hours. Integer from 1 to 72
     * @type {number}
     * @memberof SendRcsCampaignGroups
     */
    'validity'?: number;
    /**
     * Start sending the messages at
     * @type {string}
     * @memberof SendRcsCampaignGroups
     */
    'start_at'?: string;
    /**
     * 
     * @type {Options}
     * @memberof SendRcsCampaignGroups
     */
    'options': Options;
    /**
     * 
     * @type {SendRcsCampaignGroupsAlternativeChannel}
     * @memberof SendRcsCampaignGroups
     */
    'alternative_channel'?: SendRcsCampaignGroupsAlternativeChannel | null;
    /**
     * Specifies whether to add the specified phone number of the message recipient to the contact book
     * @type {boolean}
     * @memberof SendRcsCampaignGroups
     */
    'add_to_contact_book'?: boolean;
    /**
     * Check the recipient’s phone number for being in the stop list.  Possible values:    - true – if the number is found in the stop list, do not send the message  - false – ignore the stop list
     * @type {boolean}
     * @memberof SendRcsCampaignGroups
     */
    'check_stop_list'?: boolean;
}

