/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SenderRequestType } from './sender-request-type';

/**
 * 
 * @export
 * @interface SenderRequestLegalRequest
 */
export interface SenderRequestLegalRequest {
    /**
     * Country code according to ISO 3166-1 alpha-2 standard
     * @type {string}
     * @memberof SenderRequestLegalRequest
     */
    'country_code': string;
    /**
     * 
     * @type {SenderRequestType}
     * @memberof SenderRequestLegalRequest
     */
    'type': SenderRequestType;
    /**
     * Sender name.   Up to 11 Latin letters or digits, up to 15 – only digits. To setup senders visit the [account](https://app.bsg.world/sms/senders) or use [sender api](#tag/Senders)
     * @type {string}
     * @memberof SenderRequestLegalRequest
     */
    'sender': string;
    /**
     * National registration code of Company (ЄДРПОУ for Ukraine)
     * @type {string}
     * @memberof SenderRequestLegalRequest
     */
    'code_of_company': string;
    /**
     * Taxpayer number
     * @type {string}
     * @memberof SenderRequestLegalRequest
     */
    'tax_number': string;
    /**
     * Service description
     * @type {string}
     * @memberof SenderRequestLegalRequest
     */
    'description': string;
    /**
     * Purpose of informing
     * @type {string}
     * @memberof SenderRequestLegalRequest
     */
    'informing_purpose': string;
    /**
     * Website URL of your service
     * @type {string}
     * @memberof SenderRequestLegalRequest
     */
    'site_url'?: string;
    /**
     * any additional information
     * @type {string}
     * @memberof SenderRequestLegalRequest
     */
    'comment'?: string | null;
    /**
     * Legal entity name
     * @type {string}
     * @memberof SenderRequestLegalRequest
     */
    'legal_name'?: string;
    /**
     * Legal Address
     * @type {string}
     * @memberof SenderRequestLegalRequest
     */
    'address'?: string;
}



