/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SendOtpRequest
 */
export interface SendOtpRequest {
    /**
     * The phone number of the recipient of the one-time password. 9 to 15 digits without the + sign. 3 to 15 characters for the sender’s numeric name.
     * @type {string}
     * @memberof SendOtpRequest
     */
    'recipient': string;
    /**
     * A channel for sending a one-time password. Possible values: sms, viber.
     * @type {string}
     * @memberof SendOtpRequest
     */
    'channel': SendOtpRequestChannelEnum;
    /**
     * Sender’s name: from 3 to 11 characters for the sender’s alphanumeric name (Latin letters, symbols, numbers, spaces); 3 to 15 characters for the sender’s numeric name. To setup senders visit the [account](https://app.bsg.world/sms/senders)
     * @type {string}
     * @memberof SendOtpRequest
     */
    'sender': string;
    /**
     * Used only for the Viber channel to alternatively send a one-time code in SMS (if it was not possible to send the code in a Viber message, for example, if the recipient is not a Viber user).The name or number of the SMS sender. String up to 15 characters: from 3 to 11 characters for the sender’s alphanumeric name (Latin letters, symbols, numbers, spaces); 3 to 15 characters for the sender’s numeric name.
     * @type {string}
     * @memberof SendOtpRequest
     */
    'sender_alt'?: string | null;
    /**
     * Unique identifier of the [template](https://app.bsg.world/2fa/templates) with the Approved status. It’s not allowed to specify the template ID in other statuses. The template ID must be from 1 to 9 digits
     * @type {number}
     * @memberof SendOtpRequest
     */
    'template_id': number;
    /**
     * The password expiration time after which the password becomes invalid. An integer from 30 seconds to 300 seconds.
     * @type {number}
     * @memberof SendOtpRequest
     */
    'code_lifetime': number;
    /**
     * The number of password verification attempts. An integer from 1 to 5.
     * @type {number}
     * @memberof SendOtpRequest
     */
    'code_max_tries': number;
    /**
     * The length of the numeric code, from 3 to 9 digits.
     * @type {number}
     * @memberof SendOtpRequest
     */
    'code_digits': number;
}

export const SendOtpRequestChannelEnum = {
    Sms: 'sms',
    Viber: 'viber'
} as const;

export type SendOtpRequestChannelEnum = typeof SendOtpRequestChannelEnum[keyof typeof SendOtpRequestChannelEnum];


