/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Inline } from './inline';

/**
 * 
 * @export
 * @interface SendTemplateEmail
 */
export interface SendTemplateEmail {
    /**
     * List of email addresses to send the email to
     * @type {Set<string>}
     * @memberof SendTemplateEmail
     */
    'to': Set<string>;
    /**
     * The sender’s email address
     * @type {string}
     * @memberof SendTemplateEmail
     */
    'from': string;
    /**
     * ID of the email template to be used for the email’s content
     * @type {number}
     * @memberof SendTemplateEmail
     */
    'template_id': number;
    /**
     * The subject line of the email
     * @type {string}
     * @memberof SendTemplateEmail
     */
    'subject'?: string;
    /**
     * JSON object with key-value pairs for dynamic content in the email template
     * @type {{ [key: string]: string; }}
     * @memberof SendTemplateEmail
     */
    'template_content'?: { [key: string]: string; };
    /**
     * A list of inline attachments
     * @type {Array<Inline>}
     * @memberof SendTemplateEmail
     */
    'inlines'?: Array<Inline>;
}

