/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SenderRequestNaturalSchema } from './sender-request-natural-schema';

/**
 * 
 * @export
 * @interface SenderRequestNatural201Response
 */
export interface SenderRequestNatural201Response {
    /**
     * 
     * @type {SenderRequestNaturalSchema}
     * @memberof SenderRequestNatural201Response
     */
    'data'?: SenderRequestNaturalSchema;
}

