/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Inline } from './inline';

/**
 * 
 * @export
 * @interface SendEmail
 */
export interface SendEmail {
    /**
     * List of email addresses to send the email to
     * @type {Set<string>}
     * @memberof SendEmail
     */
    'to': Set<string>;
    /**
     * The sender’s email address
     * @type {string}
     * @memberof SendEmail
     */
    'from': string;
    /**
     * The subject line of the email
     * @type {string}
     * @memberof SendEmail
     */
    'subject': string;
    /**
     * Optional email body as plain text in addition to `htmlbody` for old email clients without html support
     * @type {string}
     * @memberof SendEmail
     */
    'body'?: string | null;
    /**
     * The HTML-formatted content of the email body (can include rich text elements)
     * @type {string}
     * @memberof SendEmail
     */
    'htmlbody': string | null;
    /**
     * A list of inline attachments
     * @type {Array<Inline>}
     * @memberof SendEmail
     */
    'inlines'?: Array<Inline>;
}

