/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SenderRequestSchema } from './sender-request-schema';
// May contain unused imports in some cases
// @ts-ignore
import type { SenderRequests200ResponseMeta } from './sender-requests200-response-meta';

/**
 * 
 * @export
 * @interface SenderRequests200Response
 */
export interface SenderRequests200Response {
    /**
     * 
     * @type {Array<SenderRequestSchema>}
     * @memberof SenderRequests200Response
     */
    'data'?: Array<SenderRequestSchema>;
    /**
     * 
     * @type {SenderRequests200ResponseMeta}
     * @memberof SenderRequests200Response
     */
    'meta'?: SenderRequests200ResponseMeta;
}

