/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Status of the application for Sender registration. Possible values:  - new – application created  - accepted – accepted  - in progress – in progress  - registration completed – Sender registration completed  - rejected – application for Sender registration rejected 
 * @export
 * @enum {string}
 */

export const SenderRequestStatus = {
    New: 'new',
    Accepted: 'accepted',
    InProgress: 'in_progress',
    Registered: 'registered',
    Rejected: 'rejected'
} as const;

export type SenderRequestStatus = typeof SenderRequestStatus[keyof typeof SenderRequestStatus];



