/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Sender type
 * @export
 * @enum {string}
 */

export const SenderRequestType = {
    Sms: 'sms',
    Viber: 'viber'
} as const;

export type SenderRequestType = typeof SenderRequestType[keyof typeof SenderRequestType];



