/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SenderRequestStatus } from './sender-request-status';
// May contain unused imports in some cases
// @ts-ignore
import type { SenderRequestType } from './sender-request-type';

/**
 * 
 * @export
 * @interface SenderRequestLegalSchema
 */
export interface SenderRequestLegalSchema {
    /**
     * Number of the application for Sender registration
     * @type {number}
     * @memberof SenderRequestLegalSchema
     */
    'id'?: number;
    /**
     * Sender name.   Up to 11 Latin letters or digits, up to 15 – only digits. To setup senders visit the [account](https://app.bsg.world/sms/senders) or use [sender api](#tag/Senders)
     * @type {string}
     * @memberof SenderRequestLegalSchema
     */
    'sender'?: string;
    /**
     * Legal entity name
     * @type {string}
     * @memberof SenderRequestLegalSchema
     */
    'legal_name'?: string;
    /**
     * Legal Address
     * @type {string}
     * @memberof SenderRequestLegalSchema
     */
    'address'?: string;
    /**
     * 
     * @type {SenderRequestStatus}
     * @memberof SenderRequestLegalSchema
     */
    'status'?: SenderRequestStatus;
    /**
     * 
     * @type {SenderRequestType}
     * @memberof SenderRequestLegalSchema
     */
    'type'?: SenderRequestType;
    /**
     * Date when the item was created in the system ― set by the system automatically. Display format ― Y-m-d H:i:s
     * @type {string}
     * @memberof SenderRequestLegalSchema
     */
    'created_at'?: string;
    /**
     * Country code according to ISO 3166-1 alpha-2 standard
     * @type {string}
     * @memberof SenderRequestLegalSchema
     */
    'country_code'?: string;
    /**
     * National registration code of Company (ЄДРПОУ for Ukraine)
     * @type {string}
     * @memberof SenderRequestLegalSchema
     */
    'code_of_company'?: string;
    /**
     * Taxpayer number
     * @type {string}
     * @memberof SenderRequestLegalSchema
     */
    'tax_number'?: string;
    /**
     * Website URL of your service
     * @type {string}
     * @memberof SenderRequestLegalSchema
     */
    'site_url'?: string;
    /**
     * Purpose of informing
     * @type {string}
     * @memberof SenderRequestLegalSchema
     */
    'informing_purpose'?: string;
    /**
     * any additional information
     * @type {string}
     * @memberof SenderRequestLegalSchema
     */
    'comment'?: string | null;
    /**
     * Service description
     * @type {string}
     * @memberof SenderRequestLegalSchema
     */
    'description'?: string;
}



