/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AlternativeChannel } from './alternative-channel';
// May contain unused imports in some cases
// @ts-ignore
import type { Options } from './options';
// May contain unused imports in some cases
// @ts-ignore
import type { Phone } from './phone';

/**
 * 
 * @export
 * @interface SendRcsCampaign
 */
export interface SendRcsCampaign {
    /**
     * The list of objects containing information about the mobile phone number (number) and (reference_id) to send a message to
     * @type {Array<Phone>}
     * @memberof SendRcsCampaign
     */
    'phones': Array<Phone>;
    /**
     * The name of the agent used to send the rcs message
     * @type {string}
     * @memberof SendRcsCampaign
     */
    'sender': string;
    /**
     * 
     * @type {Options}
     * @memberof SendRcsCampaign
     */
    'options': Options;
    /**
     * 
     * @type {AlternativeChannel}
     * @memberof SendRcsCampaign
     */
    'alternative_channel'?: AlternativeChannel;
    /**
     * Start sending the messages at
     * @type {string}
     * @memberof SendRcsCampaign
     */
    'start_at'?: string;
    /**
     * Tariff code null by default. Your can pass specified one if you have several. For more information please visit the [account prices](https://app.bsg.world/prices/sms)
     * @type {number}
     * @memberof SendRcsCampaign
     */
    'tariff_code'?: number;
    /**
     * Message validity period in seconds. After this period expires, the message will be in **EXPIRED** status or will be redirected to the SMS channel if it was specified in the request
     * @type {number}
     * @memberof SendRcsCampaign
     */
    'validity_seconds'?: number;
    /**
     * validity time in hours. The default is 72 hours. Integer from 1 to 72
     * @type {number}
     * @memberof SendRcsCampaign
     */
    'validity'?: number;
    /**
     * Specifies whether to add the specified phone number of the message recipient to the contact book
     * @type {boolean}
     * @memberof SendRcsCampaign
     */
    'add_to_contact_book'?: boolean;
    /**
     * Check the recipient’s phone number for being in the stop list.  Possible values:    - true – if the number is found in the stop list, do not send the message  - false – ignore the stop list
     * @type {boolean}
     * @memberof SendRcsCampaign
     */
    'check_stop_list'?: boolean;
}

