/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SenderSchema
 */
export interface SenderSchema {
    /**
     * 
     * @type {number}
     * @memberof SenderSchema
     */
    'id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SenderSchema
     */
    'status'?: SenderSchemaStatusEnum;
    /**
     * Country code according to ISO 3166-1 alpha-2 standard
     * @type {string}
     * @memberof SenderSchema
     */
    'country'?: string | null;
    /**
     * Sender name.   Up to 11 Latin letters or digits, up to 15 – only digits. To setup senders visit the [account](https://app.bsg.world/sms/senders) or use [sender api](#tag/Senders)
     * @type {string}
     * @memberof SenderSchema
     */
    'sender'?: string;
    /**
     * Date when the item was created in the system ― set by the system automatically. Display format ― Y-m-d H:i:s
     * @type {string}
     * @memberof SenderSchema
     */
    'created_at'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SenderSchema
     */
    'is_default'?: boolean;
}

export const SenderSchemaStatusEnum = {
    Active: 'active',
    Blocked: 'blocked',
    Registering: 'registering'
} as const;

export type SenderSchemaStatusEnum = typeof SenderSchemaStatusEnum[keyof typeof SenderSchemaStatusEnum];


