/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ShortLinkStatus } from './short-link-status';

/**
 * Short Link object
 * @export
 * @interface ShortUrlLinkSchema
 */
export interface ShortUrlLinkSchema {
    /**
     * short link unique id
     * @type {string}
     * @memberof ShortUrlLinkSchema
     */
    'id'?: string;
    /**
     * 
     * @type {ShortLinkStatus}
     * @memberof ShortUrlLinkSchema
     */
    'status'?: ShortLinkStatus;
    /**
     * Name of short link. like a comment
     * @type {string}
     * @memberof ShortUrlLinkSchema
     */
    'name'?: string | null;
    /**
     * part of short link after domain
     * @type {string}
     * @memberof ShortUrlLinkSchema
     */
    'slug'?: string;
    /**
     * campaign ID if short link is part of sms campaign.  Campaign allow send messages to all the leads with different short link for each lead that follows to the same original link
     * @type {number}
     * @memberof ShortUrlLinkSchema
     */
    'campaign_id'?: number;
    /**
     * message id for short links created as part of [sms campaign](#tag/Campaign-SMS)
     * @type {number}
     * @memberof ShortUrlLinkSchema
     */
    'message_id'?: number | null;
    /**
     * Date and time when short link was deactivated
     * @type {string}
     * @memberof ShortUrlLinkSchema
     */
    'init_deleted_at'?: string;
    /**
     * Date and time when short link was created
     * @type {string}
     * @memberof ShortUrlLinkSchema
     */
    'created_at'?: string;
    /**
     * short link url that can be used to redirect to original link
     * @type {string}
     * @memberof ShortUrlLinkSchema
     */
    'short_link'?: string;
    /**
     * Original link where to short link will redirect
     * @type {string}
     * @memberof ShortUrlLinkSchema
     */
    'original_link'?: string;
    /**
     * For link marked as deleted it can be restored a few time if can_restore=true
     * @type {boolean}
     * @memberof ShortUrlLinkSchema
     */
    'can_restore'?: boolean;
    /**
     * Number of clicks on a short link  *Please note: count of clicks updated with some latency*
     * @type {number}
     * @memberof ShortUrlLinkSchema
     */
    'count_clicks'?: number;
    /**
     * Number of clicks on a short link looks like human  We use some heuristics to determine is it real human or looks like bot
     * @type {number}
     * @memberof ShortUrlLinkSchema
     */
    'count_human_clicks'?: number;
    /**
     * Number of unique clicks on a short link  We use combination of ip address user-agent cookies and so on to account the same user just once
     * @type {number}
     * @memberof ShortUrlLinkSchema
     */
    'count_unique_clicks'?: number;
}



