/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ShortDomainSlugType } from './short-domain-slug-type';

/**
 * 
 * @export
 * @interface ShortUrlDomainSchema
 */
export interface ShortUrlDomainSchema {
    /**
     * Unique Id of short domain (uuid)
     * @type {string}
     * @memberof ShortUrlDomainSchema
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ShortUrlDomainSchema
     */
    'system_domain_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShortUrlDomainSchema
     */
    'status'?: ShortUrlDomainSchemaStatusEnum;
    /**
     * short domain
     * @type {string}
     * @memberof ShortUrlDomainSchema
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ShortUrlDomainSchema
     */
    'is_default'?: boolean;
    /**
     * 
     * @type {ShortDomainSlugType}
     * @memberof ShortUrlDomainSchema
     */
    'slug_type'?: ShortDomainSlugType;
    /**
     * 
     * @type {string}
     * @memberof ShortUrlDomainSchema
     */
    'init_deleted_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShortUrlDomainSchema
     */
    'created_at'?: string;
    /**
     * Url to redirect if original link return status 404 not found
     * @type {string}
     * @memberof ShortUrlDomainSchema
     */
    'not_found_page'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ShortUrlDomainSchema
     */
    'can_refresh_status'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ShortUrlDomainSchema
     */
    'can_restore'?: boolean;
    /**
     * if system_domain_id is null it is necessary to setup your dns
     * @type {string}
     * @memberof ShortUrlDomainSchema
     */
    'record_type'?: string | null;
    /**
     * if system_domain_id is null it is necessary to setup your dns
     * @type {string}
     * @memberof ShortUrlDomainSchema
     */
    'hostname'?: string | null;
    /**
     * if system_domain_id is null it is necessary to setup your dns
     * @type {string}
     * @memberof ShortUrlDomainSchema
     */
    'cname'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ShortUrlDomainSchema
     */
    'count_short_links'?: number;
}

export const ShortUrlDomainSchemaStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Deleted: 'deleted',
    Blocked: 'blocked',
    NotPaid: 'not_paid'
} as const;

export type ShortUrlDomainSchemaStatusEnum = typeof ShortUrlDomainSchemaStatusEnum[keyof typeof ShortUrlDomainSchemaStatusEnum];


