/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ClickResource } from './click-resource';

/**
 * 
 * @export
 * @interface ShortUrlsClicks200Response
 */
export interface ShortUrlsClicks200Response {
    /**
     * 
     * @type {Array<ClickResource>}
     * @memberof ShortUrlsClicks200Response
     */
    'data'?: Array<ClickResource>;
    /**
     * The total number of items matching the specified criteria
     * @type {number}
     * @memberof ShortUrlsClicks200Response
     */
    'total'?: number;
}

