/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ShortLink
 */
export interface ShortLink {
    /**
     * Target url
     * @type {string}
     * @memberof ShortLink
     */
    'link': string;
    /**
     * Word in message text that need to be replaced by generated short link
     * @type {string}
     * @memberof ShortLink
     */
    'placeholder': string;
    /**
     * List of short domain identifiers to use for generate short links to follow at target url
     * @type {Array<string>}
     * @memberof ShortLink
     */
    'domain_ids': Array<string>;
    /**
     * Change domain each X messages
     * @type {number}
     * @memberof ShortLink
     */
    'change_domain_after'?: number | null;
    /**
     * Add (https) protocol to short link or not
     * @type {boolean}
     * @memberof ShortLink
     */
    'protocol'?: boolean;
}

