/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ShortUrlsDomainCreate422Response
 */
export interface ShortUrlsDomainCreate422Response {
    /**
     * It may be one of the following:  - **short-link.exceptions.domain_exceeded_allowed_limit** - Maximum allowed domain count already reached. Please delete unused domains or upgrade tariff - **Invalid domain name** - Duplicate domain name. This domain already exists use another domain name. 
     * @type {string}
     * @memberof ShortUrlsDomainCreate422Response
     */
    'message'?: string;
}

