/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ShortLink } from './short-link';

/**
 * 
 * @export
 * @interface SmsSendGroupsRequest
 */
export interface SmsSendGroupsRequest {
    /**
     * one or several contact list id to send messages. id of the lists can be obtained: using the Get [lists API](#tag/Contact-List) in your account [Contact Book → Lists](https://app.bsg.world/addressbook/lists)
     * @type {Set<number>}
     * @memberof SmsSendGroupsRequest
     */
    'groups'?: Set<number>;
    /**
     * Sender’s name: from 3 to 11 characters for the sender’s alphanumeric name (Latin letters, symbols, numbers, spaces); 3 to 15 characters for the sender’s numeric name. To setup senders visit the [account](https://app.bsg.world/sms/senders)
     * @type {string}
     * @memberof SmsSendGroupsRequest
     */
    'sender': string;
    /**
     * SMS text, max length is 765 chars for GSM 7-bit encoding (Latin), and 355 for UCS-2
     * @type {string}
     * @memberof SmsSendGroupsRequest
     */
    'text': string;
    /**
     * Tariff code null by default. Your can pass specified one if you have several. For more information please visit the [account prices](https://app.bsg.world/prices/sms)
     * @type {number}
     * @memberof SmsSendGroupsRequest
     */
    'tariff_code'?: number;
    /**
     * validity time in hours. The default is 72 hours. Integer from 1 to 72
     * @type {number}
     * @memberof SmsSendGroupsRequest
     */
    'validity'?: number;
    /**
     * Start sending the messages at
     * @type {string}
     * @memberof SmsSendGroupsRequest
     */
    'start_at'?: string;
    /**
     * 
     * @type {Array<ShortLink>}
     * @memberof SmsSendGroupsRequest
     */
    'short_links'?: Array<ShortLink>;
    /**
     * apply transliteration to sms text if it necessary
     * @type {boolean}
     * @memberof SmsSendGroupsRequest
     */
    'transliterate'?: boolean;
}

