/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SmsSendRequestPhonesItem
 */
export interface SmsSendRequestPhonesItem {
    /**
     * Phone number without leading plus, just digits
     * @type {number}
     * @memberof SmsSendRequestPhonesItem
     */
    'number': number;
    /**
     * external unique ID. String up to 32 characters containing only alpha numeric characters.  **Please note:** messages with duplicate reference_id will be rejected
     * @type {string}
     * @memberof SmsSendRequestPhonesItem
     */
    'reference_id'?: string;
}

