/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IndividualMessageData } from './individual-message-data';

/**
 * 
 * @export
 * @interface SmsSendIndividualRequest
 */
export interface SmsSendIndividualRequest {
    /**
     * 
     * @type {Set<IndividualMessageData>}
     * @memberof SmsSendIndividualRequest
     */
    'messages': Set<IndividualMessageData>;
    /**
     * Tariff code null by default. Your can pass specified one if you have several. For more information please visit the [account prices](https://app.bsg.world/prices/sms)
     * @type {number}
     * @memberof SmsSendIndividualRequest
     */
    'tariff_code'?: number;
    /**
     * validity time in hours. The default is 72 hours. Integer from 1 to 72
     * @type {number}
     * @memberof SmsSendIndividualRequest
     */
    'validity'?: number;
    /**
     * validity time in hours. The default is 72 hours. Integer from 1 to 72
     * @type {number}
     * @memberof SmsSendIndividualRequest
     */
    'start_at'?: number;
}

