/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The object contains information about the message for alternative delivery via SMS
 * @export
 * @interface Sms
 */
export interface Sms {
    /**
     * SMS text, max length is 765 chars for GSM 7-bit encoding (Latin), and 355 for UCS-2
     * @type {string}
     * @memberof Sms
     */
    'text': string;
    /**
     * Sender name.   Up to 11 Latin letters or digits, up to 15 – only digits. To setup senders visit the [account](https://app.bsg.world/sms/senders) or use [sender api](#tag/Senders)
     * @type {string}
     * @memberof Sms
     */
    'sender': string;
    /**
     * Validity period in seconds. If not set, validity field is used
     * @type {number}
     * @memberof Sms
     */
    'validity_seconds'?: number | null;
    /**
     * validity time in hours. The default is 72 hours. Integer from 1 to 72
     * @type {number}
     * @memberof Sms
     */
    'validity'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Sms
     */
    'check_stop_list'?: boolean;
}

