/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Sorting options: asc, desc
 * @export
 * @enum {string}
 */

export const SortWay = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type SortWay = typeof SortWay[keyof typeof SortWay];



