/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StatisticsData
 */
export interface StatisticsData {
    /**
     * 
     * @type {number}
     * @memberof StatisticsData
     */
    'delivered'?: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticsData
     */
    'sent'?: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticsData
     */
    'scheduled'?: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticsData
     */
    'moderation'?: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticsData
     */
    'accepted'?: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticsData
     */
    'sending'?: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticsData
     */
    'expired'?: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticsData
     */
    'failed'?: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticsData
     */
    'undelivered'?: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticsData
     */
    'unknown'?: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticsData
     */
    'read'?: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticsData
     */
    'not_viber_user'?: number;
    /**
     * 
     * @type {number}
     * @memberof StatisticsData
     */
    'not_rcs_user'?: number;
}

