/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StopListPaginateSchema } from './stop-list-paginate-schema';

/**
 * 
 * @export
 * @interface StoplistItems200Response
 */
export interface StoplistItems200Response {
    /**
     * 
     * @type {Array<StopListPaginateSchema>}
     * @memberof StoplistItems200Response
     */
    'data'?: Array<StopListPaginateSchema>;
    /**
     * Total items count at all of the pages
     * @type {number}
     * @memberof StoplistItems200Response
     */
    'total'?: number;
}

