/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SearchOperator } from './search-operator';
// May contain unused imports in some cases
// @ts-ignore
import type { StoplistSearchField } from './stoplist-search-field';

/**
 * Search criteria
 * @export
 * @interface StoplistSearch200ResponseMetaSearch
 */
export interface StoplistSearch200ResponseMetaSearch {
    /**
     * 
     * @type {StoplistSearchField}
     * @memberof StoplistSearch200ResponseMetaSearch
     */
    'field'?: StoplistSearchField;
    /**
     * 
     * @type {SearchOperator}
     * @memberof StoplistSearch200ResponseMetaSearch
     */
    'operator'?: SearchOperator;
    /**
     * Value to to find using search[field] and search[operator]
     * @type {string}
     * @memberof StoplistSearch200ResponseMetaSearch
     */
    'value'?: string;
}



