/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StoplistAddRequest
 */
export interface StoplistAddRequest {
    /**
     * Array of the phone numbers
     * @type {Array<number>}
     * @memberof StoplistAddRequest
     */
    'phones': Array<number>;
    /**
     * Specify the stop list type
     * @type {Array<string>}
     * @memberof StoplistAddRequest
     */
    'types': Array<StoplistAddRequestTypesEnum>;
}

export const StoplistAddRequestTypesEnum = {
    Sms: 'sms',
    Viber: 'viber',
    Rcs: 'rcs',
    Whatsapp: 'whatsapp'
} as const;

export type StoplistAddRequestTypesEnum = typeof StoplistAddRequestTypesEnum[keyof typeof StoplistAddRequestTypesEnum];


