/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StopListPaginateSchema
 */
export interface StopListPaginateSchema {
    /**
     * ID of the contact added to the stop list
     * @type {number}
     * @memberof StopListPaginateSchema
     */
    'id'?: number;
    /**
     * Phone number without leading plus, just digits
     * @type {number}
     * @memberof StopListPaginateSchema
     */
    'phone'?: number;
    /**
     * Date when the item was created in the system ― set by the system automatically. Display format ― Y-m-d H:i:s
     * @type {string}
     * @memberof StopListPaginateSchema
     */
    'created_at'?: string;
    /**
     * Whether the contact was added to the SMS stop list
     * @type {boolean}
     * @memberof StopListPaginateSchema
     */
    'sms_stoplist'?: boolean;
    /**
     * Whether the contact was added to the Viber stop list
     * @type {boolean}
     * @memberof StopListPaginateSchema
     */
    'viber_stoplist'?: boolean;
    /**
     * Whether the contact was added to the Rcs stop list
     * @type {boolean}
     * @memberof StopListPaginateSchema
     */
    'rcs_stoplist'?: boolean;
}

