/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StopListCollection
 */
export interface StopListCollection {
    /**
     * 
     * @type {number}
     * @memberof StopListCollection
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof StopListCollection
     */
    'phone'?: number;
    /**
     * 
     * @type {string}
     * @memberof StopListCollection
     */
    'created_at'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof StopListCollection
     */
    'sms_stoplist'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StopListCollection
     */
    'viber_stoplist'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof StopListCollection
     */
    'rcs_stoplist'?: boolean;
}

