/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Call when click the button
 * @export
 * @interface SuggestionCall
 */
export interface SuggestionCall {
    /**
     * text of the button
     * @type {string}
     * @memberof SuggestionCall
     */
    'text': string;
    /**
     * Phone number to call with a click of a button. 9 – 15 characters (the length must take into account the country code and phone number, the phone number is indicated without +). When sending RCS messages to the country of Ukraine, the phone number to call via the button must be a Ukrainian number
     * @type {string}
     * @memberof SuggestionCall
     */
    'phone': string;
    /**
     * Extra data to send on callback_url when user click on the button
     * @type {string}
     * @memberof SuggestionCall
     */
    'postback_data'?: string;
}

