/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Redirect user to url link when click the button
 * @export
 * @interface SuggestionLink
 */
export interface SuggestionLink {
    /**
     * text of the button
     * @type {string}
     * @memberof SuggestionLink
     */
    'text': string;
    /**
     * A link to go through a click on the button. The link should start with http/https.  If you need to add a button to unsubscribe the user from the mailing list, you can specify a link in the format http://nosms.cc/XXXX – the Platform will generate an Unsubscribe link for this action when sending the message. When the user clicks on the unsubscribe button, the user’s number will be added to the RCS email stop list.
     * @type {string}
     * @memberof SuggestionLink
     */
    'url': string;
    /**
     * Extra data to send on callback_url when user click on the button
     * @type {string}
     * @memberof SuggestionLink
     */
    'postback_data'?: string;
}

