/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SuggestionCall } from './suggestion-call';
// May contain unused imports in some cases
// @ts-ignore
import type { SuggestionLink } from './suggestion-link';

/**
 * @type Suggestion
 * Object describe action when user click on button, it may be call to the phone or redirect to the link
 * @export
 */
export type Suggestion = SuggestionCall | SuggestionLink;


