/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TariffSchema
 */
export interface TariffSchema {
    /**
     * Tariff id
     * @type {number}
     * @memberof TariffSchema
     */
    'id'?: number;
    /**
     * Tariff name
     * @type {string}
     * @memberof TariffSchema
     */
    'name'?: string;
    /**
     * Tariff code null by default. Your can pass specified one if you have several. For more information please visit the [account prices](https://app.bsg.world/prices/sms)
     * @type {number}
     * @memberof TariffSchema
     */
    'code'?: number;
    /**
     * Indicates whether the tariff is active
     * @type {boolean}
     * @memberof TariffSchema
     */
    'is_active'?: boolean;
    /**
     * Indicates whether the rate is the default
     * @type {boolean}
     * @memberof TariffSchema
     */
    'is_default'?: boolean;
}

