/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TooManyRequestsResponse
 */
export interface TooManyRequestsResponse {
    /**
     * Too many duplicate request detected  It seems like you send several duplicate request in short time. Usually it have no sense to do it. PLease check your software
     * @type {string}
     * @memberof TooManyRequestsResponse
     */
    'message'?: string;
}

