/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OtpTemplateStatus } from './otp-template-status';

/**
 * 
 * @export
 * @interface TwoFaTemplateResource
 */
export interface TwoFaTemplateResource {
    /**
     * Unique, automatically generated by a system identifier of the template within the TwoFA service.
     * @type {number}
     * @memberof TwoFaTemplateResource
     */
    'template_id'?: number;
    /**
     * Name of the template.  A string of 3 to 50 characters.
     * @type {string}
     * @memberof TwoFaTemplateResource
     */
    'name'?: string;
    /**
     * The text of the template message.
     * @type {string}
     * @memberof TwoFaTemplateResource
     */
    'text'?: string;
    /**
     * Two-letter country code(s) for which the template must apply. Sending messages with the OTP code will only be possible if the recipient’s number belongs to the country you specify for the template.
     * @type {Array<string>}
     * @memberof TwoFaTemplateResource
     */
    'countries'?: Array<string>;
    /**
     * 
     * @type {OtpTemplateStatus}
     * @memberof TwoFaTemplateResource
     */
    'status'?: OtpTemplateStatus;
    /**
     * Date and time of the last change of the template in ISO 8601 format.
     * @type {string}
     * @memberof TwoFaTemplateResource
     */
    'updated_at'?: string;
}



