/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OtpChannel } from './otp-channel';
// May contain unused imports in some cases
// @ts-ignore
import type { OtpMessageStatus } from './otp-message-status';

/**
 * 
 * @export
 * @interface TwoFactorMessageResource
 */
export interface TwoFactorMessageResource {
    /**
     * The unique ID of the message
     * @type {number}
     * @memberof TwoFactorMessageResource
     */
    'id'?: number;
    /**
     * Number of the recipient of the message with a one-time code
     * @type {string}
     * @memberof TwoFactorMessageResource
     */
    'recipient'?: string;
    /**
     * 
     * @type {OtpMessageStatus}
     * @memberof TwoFactorMessageResource
     */
    'status'?: OtpMessageStatus;
    /**
     * 
     * @type {OtpChannel}
     * @memberof TwoFactorMessageResource
     */
    'channel'?: OtpChannel;
    /**
     * Sender name
     * @type {string}
     * @memberof TwoFactorMessageResource
     */
    'sender'?: string;
    /**
     * Message cost
     * @type {number}
     * @memberof TwoFactorMessageResource
     */
    'price'?: number;
    /**
     * The three-letter code of the currency in which the value is indicated. Corresponds to the user’s account currency
     * @type {string}
     * @memberof TwoFactorMessageResource
     */
    'currency'?: string;
    /**
     * The date and time of the message were sent in ISO 8601 format
     * @type {string}
     * @memberof TwoFactorMessageResource
     */
    'sent_at'?: string | null;
    /**
     * The date and time the message was created in ISO 8601 format
     * @type {string}
     * @memberof TwoFactorMessageResource
     */
    'created_at'?: string;
}



