/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OtpChannel } from './otp-channel';
// May contain unused imports in some cases
// @ts-ignore
import type { OtpStatus } from './otp-status';

/**
 * 
 * @export
 * @interface TwoFactorAuthenticationSchema
 */
export interface TwoFactorAuthenticationSchema {
    /**
     * The ID of the generated authentication
     * @type {string}
     * @memberof TwoFactorAuthenticationSchema
     */
    'id'?: string;
    /**
     * Number of the recipient of the message with a one-time code
     * @type {string}
     * @memberof TwoFactorAuthenticationSchema
     */
    'recipient'?: string;
    /**
     * 
     * @type {OtpStatus}
     * @memberof TwoFactorAuthenticationSchema
     */
    'status'?: OtpStatus;
    /**
     * 
     * @type {OtpChannel}
     * @memberof TwoFactorAuthenticationSchema
     */
    'channel'?: OtpChannel;
    /**
     * Sender name
     * @type {string}
     * @memberof TwoFactorAuthenticationSchema
     */
    'sender'?: string;
    /**
     * SMS sender name
     * @type {string}
     * @memberof TwoFactorAuthenticationSchema
     */
    'sender_alt'?: string | null;
    /**
     * Message text.
     * @type {string}
     * @memberof TwoFactorAuthenticationSchema
     */
    'message_text'?: string;
    /**
     * OTP expiration date
     * @type {number}
     * @memberof TwoFactorAuthenticationSchema
     */
    'code_lifetime'?: number;
    /**
     * The number of OTP check attempts
     * @type {number}
     * @memberof TwoFactorAuthenticationSchema
     */
    'code_max_tries'?: number;
    /**
     * The number of digits in the OTP
     * @type {number}
     * @memberof TwoFactorAuthenticationSchema
     */
    'code_digits'?: number;
    /**
     * Authentication cost. At the time of creating the authentication, 0 is indicated
     * @type {number}
     * @memberof TwoFactorAuthenticationSchema
     */
    'price'?: number;
    /**
     * The three-letter code of the currency in which the value is indicated. Corresponds to the user’s account currency
     * @type {string}
     * @memberof TwoFactorAuthenticationSchema
     */
    'currency'?: string;
    /**
     * The country code of the recipient of the one-time password according to the ISO 3166-1 alpha-2 standard
     * @type {string}
     * @memberof TwoFactorAuthenticationSchema
     */
    'country_code'?: string;
    /**
     * Date and time when the authentication expires in ISO 8601 format
     * @type {string}
     * @memberof TwoFactorAuthenticationSchema
     */
    'expired_at'?: string;
    /**
     * The date and time of the authentication session were created in ISO 8601 format
     * @type {string}
     * @memberof TwoFactorAuthenticationSchema
     */
    'created_at'?: string;
    /**
     * Date and time when the authentication session was closed. At the time of creating the authentication, the value “null” is indicated
     * @type {string}
     * @memberof TwoFactorAuthenticationSchema
     */
    'finished_at'?: string;
}



