/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ViberOptions } from './viber-options';

/**
 * 
 * @export
 * @interface Viber
 */
export interface Viber {
    /**
     * 
     * @type {string}
     * @memberof Viber
     */
    'text': string;
    /**
     * 
     * @type {string}
     * @memberof Viber
     */
    'sender': string;
    /**
     * Validity period in seconds. If not set, validity field is used
     * @type {number}
     * @memberof Viber
     */
    'validity_seconds'?: number;
    /**
     * Validity period in hours
     * @type {number}
     * @memberof Viber
     */
    'validity'?: number;
    /**
     * 
     * @type {ViberOptions}
     * @memberof Viber
     */
    'options'?: ViberOptions;
    /**
     * 
     * @type {boolean}
     * @memberof Viber
     */
    'check_stop_list'?: boolean;
}

