/* tslint:disable */
/* eslint-disable */
/**
 * One-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WstPriceSchema
 */
export interface WstPriceSchema {
    /**
     * 
     * @type {string}
     * @memberof WstPriceSchema
     */
    'country_code'?: string;
    /**
     * 
     * @type {number}
     * @memberof WstPriceSchema
     */
    'price'?: number;
    /**
     * 
     * @type {string}
     * @memberof WstPriceSchema
     */
    'currency'?: string;
}

